// src/components/duck-brain/DuckBrainInput.tsx
import React, { useState, useRef, useEffect, useCallback } from "react";
import { Send, Square, Loader2, Table2, Columns } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { cn } from "@/lib/utils";
import { estimateTokens, formatTokenCount } from "@/lib/duckBrain/tokenEstimate";
import type { DatabaseInfo } from "@/store";
import SchemaAutocomplete from "./SchemaAutocomplete";
import { buildSchemaSuggestions, type SchemaSuggestion } from "@/lib/duckBrain/schemaSuggestions";

// Render text with styled @ mentions
const renderWithMentions = (text: string) => {
  const mentionRegex = /@([\w.]+)/g;
  const parts: React.ReactNode[] = [];
  let lastIndex = 0;
  let match;

  while ((match = mentionRegex.exec(text)) !== null) {
    // Add text before the mention
    if (match.index > lastIndex) {
      parts.push(
        <span key={`text-${lastIndex}`} className="whitespace-pre-wrap">
          {text.slice(lastIndex, match.index)}
        </span>
      );
    }

    // Add the mention as a styled pill
    const mention = match[1];
    const isColumn = mention.includes(".");
    parts.push(
      <span
        key={`mention-${match.index}`}
        className="inline-flex items-center gap-0.5 px-1 py-px rounded bg-primary/20 text-primary text-xs font-medium align-baseline"
      >
        {isColumn ? <Columns className="h-3 w-3" /> : <Table2 className="h-3 w-3" />}
        {mention}
      </span>
    );

    lastIndex = match.index + match[0].length;
  }

  // Add remaining text
  if (lastIndex < text.length) {
    parts.push(
      <span key={`text-${lastIndex}`} className="whitespace-pre-wrap">
        {text.slice(lastIndex)}
      </span>
    );
  }

  return parts.length > 0 ? parts : text;
};

interface DuckBrainInputProps {
  onSend: (message: string) => void;
  onAbort?: () => void;
  isGenerating: boolean;
  disabled?: boolean;
  placeholder?: string;
  databases?: DatabaseInfo[];
  className?: string;
  /** Estimated tokens of everything sent besides the draft (schema, history, system prompt). */
  baselineTokens?: number;
}

const DuckBrainInput: React.FC<DuckBrainInputProps> = ({
  onSend,
  onAbort,
  isGenerating,
  disabled = false,
  placeholder = "Ask Duck Brain to write SQL... (@ for tables)",
  databases = [],
  className,
  baselineTokens,
}) => {
  const [input, setInput] = useState("");
  const [isAutocompleteOpen, setIsAutocompleteOpen] = useState(false);
  const [suggestions, setSuggestions] = useState<SchemaSuggestion[]>([]);
  const [activeIndex, setActiveIndex] = useState(0);
  const [mentionStart, setMentionStart] = useState<number | null>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const containerRef = useRef<HTMLFormElement>(null);

  // Auto-resize textarea
  useEffect(() => {
    const textarea = textareaRef.current;
    if (textarea) {
      textarea.style.height = "auto";
      textarea.style.height = `${Math.min(textarea.scrollHeight, 120)}px`;
    }
  }, [input]);

  // Detect @ mentions and filter suggestions
  const handleInputChange = useCallback(
    (e: React.ChangeEvent<HTMLTextAreaElement>) => {
      const value = e.target.value;
      const cursorPos = e.target.selectionStart || 0;
      setInput(value);

      // Find the @ before cursor
      const textBeforeCursor = value.slice(0, cursorPos);
      const lastAtIndex = textBeforeCursor.lastIndexOf("@");

      if (lastAtIndex !== -1) {
        // Check if there's a space between @ and cursor (mention ended)
        const textAfterAt = textBeforeCursor.slice(lastAtIndex + 1);
        const hasSpace = /\s/.test(textAfterAt);

        if (!hasSpace) {
          // Active mention - show suggestions
          setMentionStart(lastAtIndex);
          const filter = textAfterAt;
          const filtered = buildSchemaSuggestions(databases, filter);
          setSuggestions(filtered);
          setIsAutocompleteOpen(filtered.length > 0);
          setActiveIndex(0);
          return;
        }
      }

      // No active mention
      setIsAutocompleteOpen(false);
      setMentionStart(null);
    },
    [databases]
  );

  // Insert selected suggestion
  const insertSuggestion = useCallback(
    (suggestion: SchemaSuggestion) => {
      if (mentionStart === null) return;

      const before = input.slice(0, mentionStart);
      const cursorPos = textareaRef.current?.selectionStart || input.length;
      const after = input.slice(cursorPos);

      // Insert with @ prefix so it renders as a pill
      const insertText = `@${suggestion.fullPath}`;
      const newInput = `${before}${insertText} ${after}`;

      setInput(newInput);
      setIsAutocompleteOpen(false);
      setMentionStart(null);

      // Focus and set cursor position
      setTimeout(() => {
        const newCursorPos = before.length + insertText.length + 1;
        textareaRef.current?.focus();
        textareaRef.current?.setSelectionRange(newCursorPos, newCursorPos);
      }, 0);
    },
    [input, mentionStart]
  );

  const handleKeyDown = (e: React.KeyboardEvent) => {
    // Handle autocomplete navigation
    if (isAutocompleteOpen && suggestions.length > 0) {
      switch (e.key) {
        case "ArrowDown":
          e.preventDefault();
          setActiveIndex((prev) => (prev + 1) % suggestions.length);
          return;
        case "ArrowUp":
          e.preventDefault();
          setActiveIndex((prev) => (prev === 0 ? suggestions.length - 1 : prev - 1));
          return;
        case "Tab":
        case "Enter":
          if (suggestions[activeIndex]) {
            e.preventDefault();
            insertSuggestion(suggestions[activeIndex]);
            return;
          }
          break;
        case "Escape":
          e.preventDefault();
          setIsAutocompleteOpen(false);
          return;
      }
    }

    // Regular Enter to send (if not in autocomplete)
    if (e.key === "Enter" && !e.shiftKey && !isAutocompleteOpen) {
      e.preventDefault();
      handleSubmit();
    }
  };

  const handleSubmit = (e?: React.FormEvent) => {
    e?.preventDefault();
    if (!input.trim() || isGenerating || disabled) return;

    onSend(input.trim());
    setInput("");
    setIsAutocompleteOpen(false);
  };

  // Close autocomplete when clicking outside
  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (containerRef.current && !containerRef.current.contains(e.target as Node)) {
        setIsAutocompleteOpen(false);
      }
    };

    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);

  // Check if input has any @ mentions to show overlay
  const hasMentions = /@[\w.]+/.test(input);

  return (
    <form ref={containerRef} onSubmit={handleSubmit} className={cn("relative", className)}>
      {/* Visual overlay for styled mentions */}
      {hasMentions && (
        <div
          className="absolute inset-0 pointer-events-none px-3 py-[9px] text-sm overflow-hidden"
          aria-hidden="true"
        >
          <div className="whitespace-pre-wrap break-words leading-normal">
            {renderWithMentions(input)}
          </div>
        </div>
      )}
      <Textarea
        ref={textareaRef}
        value={input}
        onChange={handleInputChange}
        onKeyDown={handleKeyDown}
        placeholder={placeholder}
        disabled={disabled || isGenerating}
        className={cn(
          "min-h-[44px] max-h-[120px] resize-none pr-12",
          "text-sm placeholder:text-muted-foreground/60",
          // Make text transparent when we have mentions to show overlay
          hasMentions && "text-transparent caret-foreground"
        )}
        rows={1}
      />

      {/* Schema Autocomplete Popover */}
      <SchemaAutocomplete
        isOpen={isAutocompleteOpen}
        suggestions={suggestions}
        activeIndex={activeIndex}
        onSelect={insertSuggestion}
        position={{ top: 50, left: 0 }}
      />

      <div className="absolute right-2 bottom-2">
        {isGenerating ? (
          <Button
            type="button"
            variant="ghost"
            size="icon"
            onClick={onAbort}
            className="h-8 w-8 text-destructive hover:text-destructive"
            aria-label="Stop generating"
          >
            <Square className="h-4 w-4" />
          </Button>
        ) : (
          <Button
            type="submit"
            variant="ghost"
            size="icon"
            disabled={!input.trim() || disabled}
            className="h-8 w-8"
            aria-label="Send message"
          >
            {disabled ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}
          </Button>
        )}
      </div>

      {/* Pre-run token estimate: schema + history + prompt + current draft (#23) */}
      {baselineTokens !== undefined && (
        <div
          className="px-1 pt-1 text-[10px] text-muted-foreground select-none"
          title="Rough estimate of tokens sent with this request (schema context, chat history, system prompt, and your message)"
        >
          ~{formatTokenCount(baselineTokens + estimateTokens(input))} tokens will be sent
        </div>
      )}
    </form>
  );
};

export default DuckBrainInput;

// src/lib/components/duck-brain/DuckBrainInput.svelte
<script lang="ts">
  import { tick } from 'svelte'
  import { Send, Square } from 'lucide-svelte'
  import Button from '../common/Button.svelte'
  import Spinner from '../common/Spinner.svelte'
  import SchemaAutocomplete from './SchemaAutocomplete.svelte'
  import type { DatabaseInfo } from '@/store'
  import { estimateTokens, formatTokenCount } from '@/lib/duckBrain/tokenEstimate'
  import { buildSchemaSuggestions, type SchemaSuggestion } from '@/lib/duckBrain/schemaSuggestions'
  import { splitMentions } from '@/lib/duckBrain/chatText'

  interface Props {
    onsend: (message: string) => void
    onabort?: () => void
    generating: boolean
    disabled?: boolean
    placeholder?: string
    databases?: DatabaseInfo[]
    /** Estimated tokens of everything sent besides the draft (schema, history, system prompt). */
    baselineTokens?: number
  }

  let {
    onsend,
    onabort,
    generating,
    disabled = false,
    placeholder = 'Ask Duck Brain to write SQL... (@ for tables)',
    databases = [],
    baselineTokens,
  }: Props = $props()

  const MAX_HEIGHT = 120
  const listId = `brain-mentions-${Math.random().toString(36).slice(2, 8)}`

  let input = $state('')
  let autocompleteOpen = $state(false)
  let suggestions = $state.raw<SchemaSuggestion[]>([])
  let activeIndex = $state(0)
  let mentionStart = $state<number | null>(null)
  let scrollTop = $state(0)
  let textarea = $state<HTMLTextAreaElement | null>(null)
  let form = $state<HTMLFormElement | null>(null)

  const parts = $derived(splitMentions(input))
  const hasMentions = $derived(parts.some((part) => part.type === 'mention'))

  // Auto-resize with the draft, up to MAX_HEIGHT, then the textarea scrolls.
  $effect(() => {
    input
    if (!textarea) return
    textarea.style.height = 'auto'
    textarea.style.height = `${Math.min(textarea.scrollHeight, MAX_HEIGHT)}px`
  })

  function closeAutocomplete() {
    autocompleteOpen = false
    mentionStart = null
  }

  // Detect an @ mention under the cursor and filter the suggestions for it.
  function handleInput(e: Event & { currentTarget: HTMLTextAreaElement }) {
    const value = e.currentTarget.value
    const cursor = e.currentTarget.selectionStart ?? 0
    const beforeCursor = value.slice(0, cursor)
    const lastAt = beforeCursor.lastIndexOf('@')

    if (lastAt !== -1) {
      const afterAt = beforeCursor.slice(lastAt + 1)
      // Whitespace between @ and the cursor means the mention has ended.
      if (!/\s/.test(afterAt)) {
        const filtered = buildSchemaSuggestions(databases, afterAt)
        mentionStart = lastAt
        suggestions = filtered
        autocompleteOpen = filtered.length > 0
        activeIndex = 0
        return
      }
    }
    closeAutocomplete()
  }

  async function insertSuggestion(suggestion: SchemaSuggestion) {
    if (mentionStart === null) return

    const before = input.slice(0, mentionStart)
    const cursor = textarea?.selectionStart ?? input.length
    const after = input.slice(cursor)
    // Keep the @ prefix so the mention is highlighted and sent as typed.
    const inserted = `@${suggestion.fullPath}`

    input = `${before}${inserted} ${after}`
    closeAutocomplete()

    await tick()
    const position = before.length + inserted.length + 1
    textarea?.focus()
    textarea?.setSelectionRange(position, position)
  }

  function submit() {
    const message = input.trim()
    if (!message || generating || disabled) return
    onsend(message)
    input = ''
    closeAutocomplete()
  }

  function handleKeydown(e: KeyboardEvent) {
    if (autocompleteOpen && suggestions.length > 0) {
      switch (e.key) {
        case 'ArrowDown':
          e.preventDefault()
          activeIndex = (activeIndex + 1) % suggestions.length
          return
        case 'ArrowUp':
          e.preventDefault()
          activeIndex = activeIndex === 0 ? suggestions.length - 1 : activeIndex - 1
          return
        case 'Tab':
        case 'Enter':
          if (suggestions[activeIndex]) {
            e.preventDefault()
            void insertSuggestion(suggestions[activeIndex])
            return
          }
          break
        case 'Escape':
          // preventDefault tells the sheet this Escape was used up here.
          e.preventDefault()
          closeAutocomplete()
          return
      }
    }

    if (e.key === 'Enter' && !e.shiftKey && !e.isComposing && !autocompleteOpen) {
      e.preventDefault()
      submit()
    }
  }

  function handleDocumentMousedown(e: MouseEvent) {
    if (form && !form.contains(e.target as Node)) autocompleteOpen = false
  }
</script>

<svelte:document onmousedown={handleDocumentMousedown} />

<form
  bind:this={form}
  class="relative"
  onsubmit={(e) => {
    e.preventDefault()
    submit()
  }}
>
  <div class="relative">
    {#if hasMentions}
      <!-- Highlight layer under the caret. It must keep the exact text metrics of
           the textarea, so mentions are tinted without padding or icons. -->
      <div
        class="pointer-events-none absolute inset-0 overflow-hidden border border-transparent py-2 pl-2.5 pr-11 text-[13px] leading-relaxed text-fg"
        aria-hidden="true"
      >
        <div class="whitespace-pre-wrap break-words" style="transform: translateY(-{scrollTop}px)">
          {#each parts as part}{#if part.type === 'mention'}<span class="rounded-sm bg-accent-soft text-accent">@{part.value}</span>{:else}{part.value}{/if}{/each}
        </div>
      </div>
    {/if}

    <textarea
      bind:this={textarea}
      bind:value={input}
      rows="1"
      {placeholder}
      disabled={disabled || generating}
      role="combobox"
      aria-label="Message Duck Brain"
      aria-autocomplete="list"
      aria-expanded={autocompleteOpen}
      aria-controls={autocompleteOpen ? listId : undefined}
      aria-activedescendant={autocompleteOpen ? `${listId}-${activeIndex}` : undefined}
      class="block max-h-[120px] min-h-[36px] w-full resize-none rounded-md border border-edge bg-surface py-2 pl-2.5 pr-11 text-[13px] leading-relaxed placeholder:text-fg-4 transition-colors duration-100 hover:border-edge-strong focus:border-accent focus:outline-none disabled:cursor-not-allowed disabled:opacity-50
        {hasMentions ? 'text-transparent caret-fg' : 'text-fg'}"
      oninput={handleInput}
      onkeydown={handleKeydown}
      onscroll={(e) => (scrollTop = e.currentTarget.scrollTop)}
    ></textarea>

    <SchemaAutocomplete
      id={listId}
      open={autocompleteOpen}
      {suggestions}
      {activeIndex}
      onselect={(suggestion) => void insertSuggestion(suggestion)}
    />

    <div class="absolute bottom-1 right-1">
      {#if generating}
        <Button icon variant="ghost" size="sm" class="text-danger hover:text-danger" aria-label="Stop generating" onclick={() => onabort?.()}>
          <Square size={14} />
        </Button>
      {:else}
        <Button icon variant="ghost" size="sm" type="submit" disabled={!input.trim() || disabled} aria-label="Send message">
          {#if disabled}
            <Spinner size="sm" class="h-3.5 w-3.5" />
          {:else}
            <Send size={14} />
          {/if}
        </Button>
      {/if}
    </div>
  </div>

  <!-- Pre-run token estimate: schema + history + prompt + current draft (#23) -->
  {#if baselineTokens !== undefined}
    <div
      class="select-none px-1 pt-1 text-[10px] text-fg-3"
      title="Rough estimate of tokens sent with this request (schema context, chat history, system prompt, and your message)"
    >
      ~{formatTokenCount(baselineTokens + estimateTokens(input))} tokens will be sent
    </div>
  {/if}
</form>
