// src/lib/components/editor/ResultCompareDialog.svelte
<script lang="ts">
  import { untrack } from 'svelte'
  import { ArrowLeftRight, Scissors, Trash2 } from 'lucide-svelte'
  import Modal from '../common/Modal.svelte'
  import Button from '../common/Button.svelte'
  import Badge from '../common/Badge.svelte'
  import Select from '../common/Select.svelte'
  import Tabs, { type TabItem } from '../common/Tabs.svelte'
  import ResultGrid from './ResultGrid.svelte'
  import { duck, duckActions } from '../../stores/duck.svelte'
  import { cellText } from '../../utils/column-types'
  import { rowsToGrid } from '@/lib/resultTable/gridData'
  import {
    createResultSnapshot, diffResults, isIdentical, PIN_ROW_LIMIT, ResultDiffError,
    type ResultDiff, type ResultSnapshot,
  } from '@/lib/resultDiff'
  import type { QueryResult, ResultPin } from '@/store/types'

  interface Props {
    open: boolean
    /** The tab's current result, offered as a side next to the pins. */
    currentResult?: QueryResult | null
    onclose: () => void
  }

  let { open, currentResult, onclose }: Props = $props()

  /** Sentinel select value for the tab's live result. */
  const CURRENT = '__current__'
  /** Changed rows are rendered as a plain table, so bound how many. */
  const CHANGED_DISPLAY_LIMIT = 500

  const pins = $derived(duck((s) => s.resultPins))
  const hasCurrent = $derived(!!currentResult && !currentResult.error)

  let leftId = $state('')
  let rightId = $state('')
  let keyColumns = $state<string[]>([])
  let view = $state('changed')

  // Default sides each time it opens: the newest pin against the current
  // result, or the two newest pins when there is no current result.
  $effect(() => {
    if (!open) return
    untrack(() => {
      leftId = (hasCurrent ? pins[pins.length - 1]?.id : pins[pins.length - 2]?.id) ?? ''
      rightId = hasCurrent ? CURRENT : (pins[pins.length - 1]?.id ?? '')
      keyColumns = []
      view = 'changed'
    })
  })

  function oneLine(sql: string, max = 60): string {
    const flat = sql.replace(/\s+/g, ' ').trim()
    return flat.length > max ? `${flat.slice(0, max - 1)}…` : flat || '(empty query)'
  }

  function pinLabel(pin: ResultPin): string {
    return `${pin.pinnedAt.toLocaleTimeString()} · ${oneLine(pin.query)}`
  }

  function formatCell(value: unknown): string {
    return value === null || value === undefined ? 'NULL' : cellText(value)
  }

  const currentSnapshot = $derived(hasCurrent && currentResult ? createResultSnapshot(currentResult) : null)

  function resolve(id: string): ResultSnapshot | null {
    if (id === CURRENT) return currentSnapshot
    return pins.find((p) => p.id === id)?.snapshot ?? null
  }

  const left = $derived(resolve(leftId))
  const right = $derived(resolve(rightId))
  const commonColumns = $derived(left && right ? right.columns.filter((c) => left.columns.includes(c)) : [])
  const activeKeys = $derived(keyColumns.filter((c) => commonColumns.includes(c)))

  const outcome = $derived.by((): { diff: ResultDiff } | { error: string } | null => {
    if (!left || !right) return null
    try {
      return { diff: diffResults(left, right, { keyColumns: activeKeys }) }
    } catch (error) {
      if (error instanceof ResultDiffError) return { error: error.message }
      throw error
    }
  })

  const diff = $derived(outcome && 'diff' in outcome ? outcome.diff : null)
  // "Changed" only exists with a key; fall back rather than show nothing.
  const activeView = $derived(view === 'changed' && diff?.rows.mode !== 'keyed' ? 'added' : view)

  const sideOptions = $derived([
    ...(hasCurrent ? [{ value: CURRENT, label: 'Current result' }] : []),
    ...[...pins].reverse().map((pin) => ({ value: pin.id, label: pinLabel(pin) })),
  ])

  const viewTabs = $derived.by((): TabItem[] => {
    if (!diff) return []
    const schemaCount = diff.schema.added.length + diff.schema.removed.length + diff.schema.typeChanged.length
    return [
      ...(diff.rows.mode === 'keyed' ? [{ id: 'changed', label: 'Changed', count: diff.rows.changed.length.toLocaleString() }] : []),
      { id: 'added', label: 'Added', count: diff.rows.added.length.toLocaleString() },
      { id: 'removed', label: 'Removed', count: diff.rows.removed.length.toLocaleString() },
      { id: 'schema', label: 'Schema', count: schemaCount },
    ]
  })

  // Key columns, then only the columns that changed somewhere: a wide result
  // with one edited cell should not scroll sideways to find it.
  const changedColumns = $derived.by(() => {
    if (!diff) return []
    const touched = new Set(diff.rows.changed.flatMap((row) => row.changedColumns))
    return [...diff.rows.keyColumns, ...diff.rows.comparedColumns.filter((c) => touched.has(c))]
  })
  const changedShown = $derived(diff ? diff.rows.changed.slice(0, CHANGED_DISPLAY_LIMIT) : [])

  function toggleKey(column: string) {
    keyColumns = keyColumns.includes(column) ? keyColumns.filter((c) => c !== column) : [...keyColumns, column]
  }

  function swap() {
    const previousLeft = leftId
    leftId = rightId
    rightId = previousLeft
  }
</script>

{#snippet rowsGrid(rows: Record<string, unknown>[], empty: string)}
  {#if rows.length > 0}
    {@const grid = rowsToGrid(rows)}
    <div class="h-full overflow-hidden rounded-md border border-edge">
      <ResultGrid meta={grid.meta} data={grid.data} {rows} compact />
    </div>
  {:else}
    <p class="p-4 text-xs text-fg-3">{empty}</p>
  {/if}
{/snippet}

<Modal
  {open}
  size="xl"
  title="Compare results"
  description="Pin results from any SQL tab, then compare two of them, or a pin against the current result. Pins last for this session and keep up to {PIN_ROW_LIMIT.toLocaleString()} rows."
  {onclose}
>
  <div class="flex h-[65vh] flex-col gap-3">
    {#if pins.length === 0 || (pins.length < 2 && !hasCurrent)}
      <p class="text-[13px] text-fg-3">
        {pins.length === 0
          ? 'Nothing pinned yet. Use "Pin result" under a query result first.'
          : 'Pin one more result, or run a query, to have two sides to compare.'}
      </p>
    {:else}
      <div class="flex flex-wrap items-end gap-2">
        <label class="min-w-0 flex-1 text-xs text-fg-3">
          <span class="mb-1 block">Before</span>
          <Select size="sm" options={sideOptions} bind:value={leftId} placeholder="Pick a result" />
        </label>
        <Button icon size="sm" variant="ghost" title="Swap sides" aria-label="Swap sides" onclick={swap}>
          <ArrowLeftRight size={14} />
        </Button>
        <label class="min-w-0 flex-1 text-xs text-fg-3">
          <span class="mb-1 block">After</span>
          <Select size="sm" options={sideOptions} bind:value={rightId} placeholder="Pick a result" />
        </label>
      </div>

      {#if commonColumns.length > 0}
        <div class="text-xs text-fg-3" role="group" aria-label="Key columns">
          <span class="mb-1 block">Key columns. None selected compares whole rows.</span>
          <div class="flex max-h-16 flex-wrap gap-1 overflow-auto">
            {#each commonColumns as column (column)}
              {@const on = activeKeys.includes(column)}
              <button
                class="rounded border px-1.5 py-0.5 font-mono text-[11px] transition-colors {on ? 'border-accent bg-accent-soft text-accent' : 'border-edge text-fg-2 hover:bg-hover'}"
                aria-pressed={on}
                onclick={() => toggleKey(column)}
              >
                {column}
              </button>
            {/each}
          </div>
        </div>
      {/if}

      {#if outcome && 'error' in outcome}
        <p class="text-xs text-danger" role="alert">{outcome.error}</p>
      {/if}

      {#if diff}
        <div class="flex flex-wrap items-center gap-1.5">
          <Badge>
            Rows {diff.rowCount.left.toLocaleString()} → {diff.rowCount.right.toLocaleString()}
            ({diff.rowCount.delta >= 0 ? '+' : ''}{diff.rowCount.delta.toLocaleString()})
          </Badge>
          <Badge tone="success">+{diff.rows.added.length.toLocaleString()} added</Badge>
          <Badge tone="danger">−{diff.rows.removed.length.toLocaleString()} removed</Badge>
          {#if diff.rows.mode === 'keyed'}
            <Badge tone="warning">~{diff.rows.changed.length.toLocaleString()} changed</Badge>
          {/if}
          <Badge>{diff.rows.unchangedCount.toLocaleString()} unchanged</Badge>
          {#if isIdentical(diff)}<Badge tone="brand">Identical</Badge>{/if}
        </div>

        {#if diff.partial}
          <div class="flex items-start gap-2 rounded-md border border-warning/40 bg-warning-soft px-3 py-2 text-xs text-fg-2">
            <Scissors size={13} class="mt-0.5 shrink-0 text-warning" />
            <span>
              At least one side holds only part of its result (pins keep the first
              {PIN_ROW_LIMIT.toLocaleString()} rows, and the engine row limit may have applied).
              Row-level differences cover the captured rows only.
            </span>
          </div>
        {/if}
        {#if diff.rows.duplicateKeys.left > 0 || diff.rows.duplicateKeys.right > 0}
          <p class="text-xs text-warning">
            The key is not unique ({diff.rows.duplicateKeys.left} duplicate(s) before,
            {diff.rows.duplicateKeys.right} after); duplicates are paired in row order.
          </p>
        {/if}

        <Tabs items={viewTabs} value={activeView} onchange={(id) => (view = id)} variant="segmented" />

        <div class="min-h-0 flex-1">
          {#if activeView === 'changed'}
            {#if diff.rows.changed.length === 0}
              <p class="p-4 text-xs text-fg-3">No changed rows.</p>
            {:else}
              <div class="flex h-full flex-col">
                {#if diff.rows.changed.length > changedShown.length}
                  <p class="px-2 py-1 text-xs text-fg-3">
                    Showing the first {changedShown.length.toLocaleString()} of
                    {diff.rows.changed.length.toLocaleString()} changed rows.
                  </p>
                {/if}
                <div class="min-h-0 flex-1 overflow-auto rounded-md border border-edge">
                  <table class="ds-table text-xs">
                    <thead class="sticky top-0 bg-surface">
                      <tr class="ds-table-head-row">
                        {#each changedColumns as column (column)}
                          <th class="ds-table-th-compact">
                            {column}
                            {#if diff.rows.keyColumns.includes(column)}
                              <span class="ml-1 rounded border border-edge px-1 text-[10px] text-fg-3">key</span>
                            {/if}
                          </th>
                        {/each}
                      </tr>
                    </thead>
                    <tbody>
                      {#each changedShown as row}
                        <tr class="ds-table-row-static">
                          {#each changedColumns as column (column)}
                            {@const isChanged = row.changedColumns.includes(column)}
                            <td class="px-2 py-1 align-top font-mono {isChanged ? 'bg-warning-soft' : 'text-fg-2'}">
                              {#if isChanged}
                                <span class="block text-danger line-through">{formatCell(row.before[column])}</span>
                                <span class="block text-success">{formatCell(row.after[column])}</span>
                              {:else}
                                {formatCell(row.after[column])}
                              {/if}
                            </td>
                          {/each}
                        </tr>
                      {/each}
                    </tbody>
                  </table>
                </div>
              </div>
            {/if}
          {:else if activeView === 'added'}
            {@render rowsGrid(diff.rows.added, 'No added rows.')}
          {:else if activeView === 'removed'}
            {@render rowsGrid(diff.rows.removed, 'No removed rows.')}
          {:else}
            {@const schema = diff.schema}
            <div class="h-full overflow-auto">
              {#if schema.added.length + schema.removed.length + schema.typeChanged.length === 0}
                <p class="p-4 text-xs text-fg-3">
                  Same columns and types{schema.reordered ? ', in a different order' : ''}.
                </p>
              {:else}
                <div class="space-y-1 p-2 font-mono text-xs">
                  {#each schema.added as c (c.name)}
                    <div class="text-success">+ {c.name} {c.type}</div>
                  {/each}
                  {#each schema.removed as c (c.name)}
                    <div class="text-danger">− {c.name} {c.type}</div>
                  {/each}
                  {#each schema.typeChanged as c (c.name)}
                    <div class="text-warning">~ {c.name}: {c.from || '?'} → {c.to || '?'}</div>
                  {/each}
                  {#if schema.reordered}
                    <div class="text-fg-3">Column order also differs.</div>
                  {/if}
                </div>
              {/if}
            </div>
          {/if}
        </div>
      {/if}
    {/if}

    {#if pins.length > 0}
      <details class="shrink-0 text-xs">
        <summary class="cursor-pointer text-fg-3">Pinned results ({pins.length})</summary>
        <ul class="mt-1 max-h-32 space-y-1 overflow-auto">
          {#each [...pins].reverse() as pin (pin.id)}
            <li class="flex items-center gap-2">
              <span class="min-w-0 flex-1 truncate text-fg-2" title={pin.query}>{pinLabel(pin)}</span>
              <span class="shrink-0 tabular-nums text-fg-3">
                {pin.snapshot.rows.length.toLocaleString()} rows{pin.snapshot.truncated ? ' (partial)' : ''}
              </span>
              <Button icon size="xs" variant="ghost" title="Remove pin" aria-label="Remove pin" onclick={() => duckActions().removeResultPin(pin.id)}>
                <Trash2 size={13} />
              </Button>
            </li>
          {/each}
        </ul>
      </details>
    {/if}
  </div>
</Modal>

// src/components/workspace/ResultCompareDialog.tsx
import { useMemo, useState } from "react";
import { useDuckStore, type QueryResult, type ResultPin } from "@/store";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Label } from "@/components/ui/label";
import { MultiSelect } from "@/components/ui/multi-select";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import DuckUiTable from "@/components/table/DuckUItable";
import { ArrowLeftRight, GitCompare, Scissors, Trash2 } from "lucide-react";
import {
  createResultSnapshot,
  diffResults,
  isIdentical,
  PIN_ROW_LIMIT,
  ResultDiffError,
  type ChangedRow,
  type ResultDiff,
  type ResultSnapshot,
} from "@/lib/resultDiff";
import { formatTimestampUTC } from "@/lib/datetime";

/** Sentinel select value for the tab's live result. */
const CURRENT = "__current__";
/** Changed rows are rendered as a plain table, so bound how many. */
const CHANGED_DISPLAY_LIMIT = 500;

interface ResultCompareDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  /** The tab's current result, offered as a side next to the pins. */
  currentResult?: QueryResult | null;
}

const oneLine = (sql: string, max = 60): string => {
  const flat = sql.replace(/\s+/g, " ").trim();
  return flat.length > max ? `${flat.slice(0, max - 1)}…` : flat || "(empty query)";
};

const pinLabel = (pin: ResultPin): string =>
  `${pin.pinnedAt.toLocaleTimeString()} · ${oneLine(pin.query)}`;

const formatCell = (value: unknown): string => {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "bigint") return value.toString();
  if (value instanceof Date) return formatTimestampUTC(value);
  if (typeof value === "object") {
    try {
      return JSON.stringify(value, (_, v) => (typeof v === "bigint" ? v.toString() : v));
    } catch {
      return String(value);
    }
  }
  return String(value);
};

const SidePicker = ({
  label,
  value,
  onChange,
  pins,
  hasCurrent,
}: {
  label: string;
  value: string;
  onChange: (value: string) => void;
  pins: ResultPin[];
  hasCurrent: boolean;
}) => (
  <div className="flex-1 min-w-0 space-y-1">
    <Label className="text-xs text-muted-foreground">{label}</Label>
    <Select value={value} onValueChange={onChange}>
      <SelectTrigger className="h-8 text-xs">
        <SelectValue placeholder="Pick a result" />
      </SelectTrigger>
      <SelectContent>
        {hasCurrent && (
          <SelectItem value={CURRENT} className="text-xs">
            Current result
          </SelectItem>
        )}
        {[...pins].reverse().map((pin) => (
          <SelectItem key={pin.id} value={pin.id} className="text-xs">
            {pinLabel(pin)}
          </SelectItem>
        ))}
      </SelectContent>
    </Select>
  </div>
);

const ChangedRowsTable = ({ diff }: { diff: ResultDiff }) => {
  const { keyColumns, comparedColumns, changed } = diff.rows;
  // Key columns, then only the columns that changed somewhere — a wide result
  // with one edited cell should not scroll sideways to find it.
  const touched = new Set(changed.flatMap((row) => row.changedColumns));
  const columns = [...keyColumns, ...comparedColumns.filter((c) => touched.has(c))];
  const shown: ChangedRow[] = changed.slice(0, CHANGED_DISPLAY_LIMIT);

  if (changed.length === 0) {
    return <p className="p-4 text-xs text-muted-foreground">No changed rows.</p>;
  }

  return (
    <div className="flex h-full flex-col">
      {changed.length > shown.length && (
        <p className="px-2 py-1 text-xs text-muted-foreground">
          Showing the first {shown.length.toLocaleString()} of {changed.length.toLocaleString()}{" "}
          changed rows.
        </p>
      )}
      <div className="min-h-0 flex-1 overflow-auto rounded-md border">
        <Table className="text-xs">
          <TableHeader className="sticky top-0 bg-background">
            <TableRow>
              {columns.map((c) => (
                <TableHead key={c} className="h-8 whitespace-nowrap text-xs">
                  {c}
                  {keyColumns.includes(c) && (
                    <Badge variant="outline" className="ml-1 px-1 py-0 text-[10px]">
                      key
                    </Badge>
                  )}
                </TableHead>
              ))}
            </TableRow>
          </TableHeader>
          <TableBody>
            {shown.map((row, i) => (
              <TableRow key={i}>
                {columns.map((c) => {
                  const isChanged = row.changedColumns.includes(c);
                  return (
                    <TableCell
                      key={c}
                      className={
                        isChanged
                          ? "bg-amber-500/15 py-1 font-mono align-top"
                          : "py-1 font-mono align-top"
                      }
                    >
                      {isChanged ? (
                        <div className="flex flex-col">
                          <span className="text-red-600 line-through dark:text-red-400">
                            {formatCell(row.before[c])}
                          </span>
                          <span className="text-green-700 dark:text-green-400">
                            {formatCell(row.after[c])}
                          </span>
                        </div>
                      ) : (
                        formatCell(row.after[c])
                      )}
                    </TableCell>
                  );
                })}
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
    </div>
  );
};

const SchemaChanges = ({ diff }: { diff: ResultDiff }) => {
  const { added, removed, typeChanged, reordered } = diff.schema;
  if (added.length + removed.length + typeChanged.length === 0) {
    return (
      <p className="p-4 text-xs text-muted-foreground">
        Same columns and types{reordered ? ", in a different order" : ""}.
      </p>
    );
  }
  return (
    <div className="space-y-1 p-2 font-mono text-xs">
      {added.map((c) => (
        <div key={`a-${c.name}`} className="text-green-700 dark:text-green-400">
          + {c.name} {c.type}
        </div>
      ))}
      {removed.map((c) => (
        <div key={`r-${c.name}`} className="text-red-600 dark:text-red-400">
          − {c.name} {c.type}
        </div>
      ))}
      {typeChanged.map((c) => (
        <div key={`t-${c.name}`} className="text-amber-600 dark:text-amber-400">
          ~ {c.name}: {c.from || "?"} → {c.to || "?"}
        </div>
      ))}
      {reordered && <div className="text-muted-foreground">Column order also differs.</div>}
    </div>
  );
};

/**
 * Compare two pinned results, or a pin against the tab's current result.
 * The diff itself lives in `lib/resultDiff`; this only picks the sides and
 * renders what comes back.
 */
export default function ResultCompareDialog({
  open,
  onOpenChange,
  currentResult,
}: ResultCompareDialogProps) {
  const pins = useDuckStore((s) => s.resultPins);
  const removeResultPin = useDuckStore((s) => s.removeResultPin);

  const hasCurrent = !!currentResult && !currentResult.error;
  // Default sides: the newest pin against the current result, or the two
  // newest pins when there is no current result. The parent mounts this only
  // while open, so these initialise afresh each time it opens.
  const [leftId, setLeftId] = useState<string>(
    () => (hasCurrent ? pins[pins.length - 1]?.id : pins[pins.length - 2]?.id) ?? ""
  );
  const [rightId, setRightId] = useState<string>(() =>
    hasCurrent ? CURRENT : (pins[pins.length - 1]?.id ?? "")
  );
  const [keyColumns, setKeyColumns] = useState<string[]>([]);
  const [view, setView] = useState<string>("changed");

  const currentSnapshot = useMemo(
    () => (hasCurrent && currentResult ? createResultSnapshot(currentResult) : null),
    [hasCurrent, currentResult]
  );

  const resolve = (id: string): ResultSnapshot | null => {
    if (id === CURRENT) return currentSnapshot;
    return pins.find((p) => p.id === id)?.snapshot ?? null;
  };
  const left = resolve(leftId);
  const right = resolve(rightId);

  const commonColumns = useMemo(
    () => (left && right ? right.columns.filter((c) => left.columns.includes(c)) : []),
    [left, right]
  );
  const activeKeys = useMemo(
    () => keyColumns.filter((c) => commonColumns.includes(c)),
    [keyColumns, commonColumns]
  );

  const outcome = useMemo((): { diff: ResultDiff } | { error: string } | null => {
    if (!left || !right) return null;
    try {
      return { diff: diffResults(left, right, { keyColumns: activeKeys }) };
    } catch (error) {
      if (error instanceof ResultDiffError) return { error: error.message };
      throw error;
    }
  }, [left, right, activeKeys]);

  const diff = outcome && "diff" in outcome ? outcome.diff : null;
  // "Changed" only exists with a key; fall back rather than show nothing.
  const activeView = view === "changed" && diff?.rows.mode !== "keyed" ? "added" : view;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="flex h-[85vh] max-w-6xl flex-col gap-3">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <GitCompare className="h-4 w-4" />
            Compare results
          </DialogTitle>
          <DialogDescription>
            Pin results from any SQL tab, then compare two of them — or a pin against the current
            result. Pins last for this session and keep up to {PIN_ROW_LIMIT.toLocaleString()} rows.
          </DialogDescription>
        </DialogHeader>

        {pins.length === 0 || (pins.length < 2 && !hasCurrent) ? (
          <p className="text-sm text-muted-foreground">
            {pins.length === 0
              ? "Nothing pinned yet. Use “Pin result” under a query result first."
              : "Pin one more result, or run a query, to have two sides to compare."}
          </p>
        ) : (
          <>
            <div className="flex items-end gap-2">
              <SidePicker
                label="Before"
                value={leftId}
                onChange={setLeftId}
                pins={pins}
                hasCurrent={hasCurrent}
              />
              <Button
                size="sm"
                variant="ghost"
                className="h-8 w-8 p-0"
                title="Swap sides"
                aria-label="Swap sides"
                onClick={() => {
                  setLeftId(rightId);
                  setRightId(leftId);
                }}
              >
                <ArrowLeftRight className="h-4 w-4" />
              </Button>
              <SidePicker
                label="After"
                value={rightId}
                onChange={setRightId}
                pins={pins}
                hasCurrent={hasCurrent}
              />
              <div className="flex-1 min-w-0 space-y-1">
                <Label className="text-xs text-muted-foreground">
                  Key column(s) — empty compares whole rows
                </Label>
                <MultiSelect
                  options={commonColumns.map((c) => ({ label: c, value: c }))}
                  selected={activeKeys}
                  onChange={setKeyColumns}
                  placeholder="No key"
                  className="min-h-8 text-xs"
                />
              </div>
            </div>

            {outcome && "error" in outcome && (
              <p className="text-xs text-destructive">{outcome.error}</p>
            )}

            {diff && (
              <>
                <div className="flex flex-wrap items-center gap-2 text-xs">
                  <Badge variant="outline">
                    Rows {diff.rowCount.left.toLocaleString()} →{" "}
                    {diff.rowCount.right.toLocaleString()} ({diff.rowCount.delta >= 0 ? "+" : ""}
                    {diff.rowCount.delta.toLocaleString()})
                  </Badge>
                  <Badge variant="outline" className="text-green-700 dark:text-green-400">
                    +{diff.rows.added.length.toLocaleString()} added
                  </Badge>
                  <Badge variant="outline" className="text-red-600 dark:text-red-400">
                    −{diff.rows.removed.length.toLocaleString()} removed
                  </Badge>
                  {diff.rows.mode === "keyed" && (
                    <Badge variant="outline" className="text-amber-600 dark:text-amber-400">
                      ~{diff.rows.changed.length.toLocaleString()} changed
                    </Badge>
                  )}
                  <Badge variant="outline">
                    {diff.rows.unchangedCount.toLocaleString()} unchanged
                  </Badge>
                  {isIdentical(diff) && <Badge>Identical</Badge>}
                </div>

                {diff.partial && (
                  <div className="flex items-start gap-2 rounded-md border border-amber-500/40 bg-amber-500/10 px-3 py-2 text-xs">
                    <Scissors className="mt-0.5 h-3.5 w-3.5 shrink-0 text-amber-500" />
                    <span>
                      At least one side holds only part of its result (pins keep the first{" "}
                      {PIN_ROW_LIMIT.toLocaleString()} rows, and the engine row limit may have
                      applied). Row-level differences cover the captured rows only.
                    </span>
                  </div>
                )}
                {(diff.rows.duplicateKeys.left > 0 || diff.rows.duplicateKeys.right > 0) && (
                  <p className="text-xs text-amber-600 dark:text-amber-400">
                    The key is not unique ({diff.rows.duplicateKeys.left} duplicate(s) before,{" "}
                    {diff.rows.duplicateKeys.right} after); duplicates are paired in row order.
                  </p>
                )}

                <Tabs
                  value={activeView}
                  onValueChange={setView}
                  className="flex min-h-0 flex-1 flex-col"
                >
                  <TabsList className="h-8 w-fit">
                    {diff.rows.mode === "keyed" && (
                      <TabsTrigger value="changed" className="h-6 text-xs">
                        Changed ({diff.rows.changed.length.toLocaleString()})
                      </TabsTrigger>
                    )}
                    <TabsTrigger value="added" className="h-6 text-xs">
                      Added ({diff.rows.added.length.toLocaleString()})
                    </TabsTrigger>
                    <TabsTrigger value="removed" className="h-6 text-xs">
                      Removed ({diff.rows.removed.length.toLocaleString()})
                    </TabsTrigger>
                    <TabsTrigger value="schema" className="h-6 text-xs">
                      Schema (
                      {diff.schema.added.length +
                        diff.schema.removed.length +
                        diff.schema.typeChanged.length}
                      )
                    </TabsTrigger>
                  </TabsList>
                  {diff.rows.mode === "keyed" && (
                    <TabsContent value="changed" className="mt-2 min-h-0 flex-1">
                      <ChangedRowsTable diff={diff} />
                    </TabsContent>
                  )}
                  <TabsContent value="added" className="mt-2 min-h-0 flex-1">
                    {diff.rows.added.length > 0 ? (
                      <div className="h-full">
                        <DuckUiTable data={diff.rows.added} />
                      </div>
                    ) : (
                      <p className="p-4 text-xs text-muted-foreground">No added rows.</p>
                    )}
                  </TabsContent>
                  <TabsContent value="removed" className="mt-2 min-h-0 flex-1">
                    {diff.rows.removed.length > 0 ? (
                      <div className="h-full">
                        <DuckUiTable data={diff.rows.removed} />
                      </div>
                    ) : (
                      <p className="p-4 text-xs text-muted-foreground">No removed rows.</p>
                    )}
                  </TabsContent>
                  <TabsContent value="schema" className="mt-2 min-h-0 flex-1 overflow-auto">
                    <SchemaChanges diff={diff} />
                  </TabsContent>
                </Tabs>
              </>
            )}
          </>
        )}

        {pins.length > 0 && (
          <details className="text-xs">
            <summary className="cursor-pointer text-muted-foreground">
              Pinned results ({pins.length})
            </summary>
            <ul className="mt-1 max-h-32 space-y-1 overflow-auto">
              {[...pins].reverse().map((pin) => (
                <li key={pin.id} className="flex items-center gap-2">
                  <span className="min-w-0 flex-1 truncate" title={pin.query}>
                    {pinLabel(pin)}
                  </span>
                  <span className="shrink-0 tabular-nums text-muted-foreground">
                    {pin.snapshot.rows.length.toLocaleString()} rows
                    {pin.snapshot.truncated ? " (partial)" : ""}
                  </span>
                  <Button
                    size="sm"
                    variant="ghost"
                    className="h-6 w-6 p-0"
                    title="Remove pin"
                    aria-label="Remove pin"
                    onClick={() => removeResultPin(pin.id)}
                  >
                    <Trash2 className="h-3.5 w-3.5" />
                  </Button>
                </li>
              ))}
            </ul>
          </details>
        )}
      </DialogContent>
    </Dialog>
  );
}
