// src/lib/components/workspace/SqlTab.svelte
<script lang="ts">
  import { Play, Square, ListTree, WandSparkles, Pin, GitCompare, Keyboard, Brain, Sparkles, ChartColumn, Map as MapIcon } from 'lucide-svelte'
  import Button from '../common/Button.svelte'
  import Tooltip from '../common/Tooltip.svelte'
  import CodeEditor from '../editor/CodeEditor.svelte'
  import QueryParamsBar from '../editor/QueryParamsBar.svelte'
  import ResultPanel from '../editor/ResultPanel.svelte'
  import ExplainPlanViewer from '../editor/ExplainPlanViewer.svelte'
  import ResultCompareDialog from '../editor/ResultCompareDialog.svelte'
  import ChartView from '../charts/ChartView.svelte'
  import Spinner from '../common/Spinner.svelte'
  import BrainResultActions from '../duck-brain/BrainResultActions.svelte'
  import { duck, duckActions } from '../../stores/duck.svelte'
  import * as toast from '../../stores/toast.svelte'
  import { listParameterNames, missingParamsMessage, resolveQueryParams } from '@/lib/sqlParams'
  import { extractPlanText } from '@/lib/explainPlan'
  import { PIN_ROW_LIMIT } from '@/lib/resultDiff'
  import { getUiConfig } from '@/lib/appConfig'
  import { findGeometryColumns } from '@/lib/geoResult'

  interface Props {
    tabId: string
  }

  let { tabId }: Props = $props()

  const SPLIT_KEY = 'duck-ui-split-percent'
  const MIN_SPLIT = 15
  const MAX_SPLIT = 85
  const isMac = /Mac/.test(navigator.platform)
  const mod = isMac ? '⌘' : 'Ctrl'

  const tab = $derived(duck((s) => s.tabs.find((t) => t.id === tabId)))
  const sqlText = $derived(typeof tab?.content === 'string' ? tab.content : '')
  const executing = $derived(duck((s) => !!s.executingTabs[tabId]))
  const progress = $derived(duck((s) => s.queryProgress[tabId]))
  const pinCount = $derived(duck((s) => s.resultPins.length))
  const paramNames = $derived(listParameterNames(sqlText))
  const brainOpen = $derived(duck((s) => s.duckBrain.isPanelOpen))
  const ui = getUiConfig()
  // Cheap: a scan of the column types, not the rows.
  const geometryColumns = $derived(tab?.result && !tab.result.error ? findGeometryColumns(tab.result) : [])
  // A rerun without a GEOMETRY column drops the Map view; the panel falls back to the table.
  const extraViews = $derived([
    { id: 'charts', label: 'Charts', icon: ChartColumn },
    ...(geometryColumns.length > 0 ? [{ id: 'map', label: 'Map', icon: MapIcon }] : []),
  ])

  let editor: CodeEditor | undefined = $state()
  let containerEl: HTMLDivElement | undefined = $state()
  let resultView = $state('table')
  let explainOpen = $state(false)
  let explainText = $state('')
  let explaining = $state(false)
  let compareOpen = $state(false)
  let resizing = $state(false)
  let fixing = $state(false)

  const savedSplit = parseFloat(localStorage.getItem(SPLIT_KEY) ?? '')
  let splitPercent = $state(Number.isNaN(savedSplit) ? 45 : savedSplit)

  function currentSql(): string {
    return (editor?.getValue() ?? sqlText).trim()
  }

  async function run(sql: string) {
    if (executing) return
    if (!sql) {
      toast.warning('Write a query first')
      return
    }
    try {
      await duckActions().executeQuery(sql, tabId)
    } catch (error) {
      console.error('Query execution failed:', error)
      toast.error('Query execution failed')
    }
  }

  async function cancel() {
    try {
      await duckActions().cancelQuery(tabId)
      toast.info('Query cancelled')
    } catch (error) {
      console.error('Failed to cancel query:', error)
    }
  }

  async function explain() {
    const query = currentSql()
    if (!query || executing) return

    // Running without a tab id (below) skips executeQuery's parameter step,
    // so resolve `$name` placeholders here with this tab's values.
    const resolved = resolveQueryParams(query, tab?.queryParams)
    if (resolved.sql === null) {
      toast.error(missingParamsMessage(resolved.missing))
      return
    }

    explaining = true
    try {
      // No tab id, so the plan is returned without replacing the tab's result.
      const result = await duckActions().executeQuery(`EXPLAIN ANALYZE ${resolved.sql}`)
      if (result?.error) {
        toast.error(result.error)
      } else if (result && result.data.length > 0) {
        explainText = extractPlanText(result.data)
        explainOpen = true
      }
    } catch (error) {
      console.error('Explain failed:', error)
      toast.error('Explain query failed')
    } finally {
      explaining = false
    }
  }

  async function fixWithBrain() {
    const error = tab?.result?.error
    if (!error || !sqlText) return
    fixing = true
    try {
      const { buildFixQueryRequest } = await import('@/lib/duckBrain')
      const fixed = await duckActions().generateSQL(buildFixQueryRequest(sqlText, error))
      if (fixed) {
        duckActions().updateTabQuery(tabId, fixed)
        toast.success('Duck Brain suggested a fix. Review it and run again')
      }
    } finally {
      fixing = false
    }
  }

  function pinResult() {
    if (!tab?.result || tab.result.error) return
    const pin = duckActions().pinResult(tabId, sqlText, tab.result)
    const { rows, sourceRowCount, truncated } = pin.snapshot
    if (truncated) {
      toast.warning(
        `Pinned ${rows.length.toLocaleString()} of ${sourceRowCount.toLocaleString()} rows. ` +
          (rows.length >= PIN_ROW_LIMIT
            ? `Pins keep at most ${PIN_ROW_LIMIT.toLocaleString()}`
            : 'The result itself was truncated'),
      )
    } else {
      toast.success(`Pinned ${rows.length.toLocaleString()} rows for comparison`)
    }
  }

  function onResizeStart(e: MouseEvent) {
    e.preventDefault()
    resizing = true
    document.addEventListener('mousemove', onResizeMove)
    document.addEventListener('mouseup', onResizeEnd)
  }

  function onResizeMove(e: MouseEvent) {
    if (!containerEl) return
    const rect = containerEl.getBoundingClientRect()
    splitPercent = Math.max(MIN_SPLIT, Math.min(MAX_SPLIT, ((e.clientY - rect.top) / rect.height) * 100))
  }

  function onResizeEnd() {
    resizing = false
    localStorage.setItem(SPLIT_KEY, splitPercent.toFixed(1))
    document.removeEventListener('mousemove', onResizeMove)
    document.removeEventListener('mouseup', onResizeEnd)
  }
</script>

{#if tab && tab.type === 'sql'}
  <div bind:this={containerEl} class="flex h-full flex-col">
    <div class="flex min-h-0 flex-col" style="height: {splitPercent}%">
      <div class="flex h-10 shrink-0 items-center gap-1 border-b border-edge-subtle px-2">
        {#if executing}
          <Button size="sm" variant="danger" onclick={cancel}>
            <Square size={12} />
            Stop
          </Button>
        {:else}
          <Button size="sm" onclick={() => run(currentSql())} title="Run query ({mod}+Enter)">
            <Play size={12} />
            Run
          </Button>
        {/if}

        <span class="mx-1 h-4 w-px bg-edge"></span>

        <Button size="sm" variant="ghost" onclick={() => editor?.format()} title="Format SQL (Alt+F)" disabled={!sqlText.trim()}>
          <WandSparkles size={13} />
          Format
        </Button>
        <Button size="sm" variant="ghost" onclick={explain} title="Explain analyze" disabled={executing || !sqlText.trim()} loading={explaining}>
          {#if !explaining}<ListTree size={13} />{/if}
          Explain
        </Button>

        <div class="ml-auto flex items-center">
          {#if !ui.hideBrain}
            <Button
              size="sm"
              variant="ghost"
              class={brainOpen ? 'text-accent' : ''}
              aria-pressed={brainOpen}
              onclick={() => duckActions().toggleBrainPanel()}
              title="Ask Duck Brain"
            >
              <Brain size={13} />
              Duck Brain
            </Button>
          {/if}
          <Tooltip text="Run query: {mod}+Enter. Run selection: {mod}+Shift+Enter. Format: Alt+F. Search: {mod}+F." side="bottom">
            <span class="inline-flex h-7 w-7 items-center justify-center text-fg-4"><Keyboard size={14} /></span>
          </Tooltip>
        </div>
      </div>

      <div class="min-h-0 flex-1">
        <CodeEditor
          bind:this={editor}
          value={sqlText}
          language="sql"
          ariaLabel="SQL editor for {tab.title}"
          placeholder="SELECT * FROM ..."
          onchange={(text) => duckActions().updateTabQuery(tabId, text)}
          onrun={run}
          onrunselection={run}
        />
      </div>
    </div>

    <!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
    <div
      class="group/split flex h-1 shrink-0 cursor-row-resize items-center justify-center transition-colors hover:bg-active {resizing ? 'bg-accent/60' : 'bg-edge-subtle'}"
      role="separator"
      aria-orientation="horizontal"
      aria-label="Resize editor and results"
      onmousedown={onResizeStart}
      ondblclick={() => (splitPercent = 45)}
    >
      <div class="h-0.5 w-8 rounded-full transition-colors {resizing ? 'bg-accent' : 'bg-edge-strong group-hover/split:bg-accent/60'}"></div>
    </div>

    <div class="flex min-h-0 flex-1 flex-col">
      <QueryParamsBar {tabId} names={paramNames} />
      <div class="min-h-0 flex-1">
        <ResultPanel
          result={tab.result}
          {executing}
          {progress}
          view={resultView}
          onviewchange={(v) => (resultView = v)}
          oncancel={cancel}
          {extraViews}
        >
          {#snippet extra(view, result)}
            {#if view === 'map'}
              <!-- Loaded on first use so maplibre stays out of the main bundle. -->
              {#await import('../map/GeoMapView.svelte')}
                <div class="flex h-full items-center justify-center"><Spinner /></div>
              {:then { default: GeoMapView }}
                <GeoMapView {result} {geometryColumns} />
              {:catch}
                <p class="p-4 text-xs text-danger" role="alert">The map could not be loaded.</p>
              {/await}
            {:else}
              <ChartView
                {result}
                chartConfig={tab.chartConfig}
                onconfigchange={(config) => duckActions().updateTabChartConfig(tabId, config)}
              />
            {/if}
          {/snippet}
          {#snippet errorActions()}
            {#if !ui.hideBrain}
              <Button size="sm" variant="outline" onclick={fixWithBrain} loading={fixing}>
                {#if !fixing}<Sparkles size={13} />{/if}
                {fixing ? 'Duck Brain is thinking...' : 'Fix with Duck Brain'}
              </Button>
            {/if}
          {/snippet}
          {#snippet actions(result)}
            <BrainResultActions {tabId} sql={sqlText} {result} onchartapplied={() => (resultView = 'charts')} />
            <Button size="xs" variant="ghost" onclick={pinResult} title="Keep a copy of this result to compare against later">
              <Pin size={13} />
              Pin result
            </Button>
            <Button size="xs" variant="ghost" onclick={() => (compareOpen = true)} disabled={pinCount === 0}>
              <GitCompare size={13} />
              Compare{pinCount > 0 ? ` (${pinCount})` : ''}
            </Button>
          {/snippet}
        </ResultPanel>
      </div>
    </div>
  </div>

  <ExplainPlanViewer open={explainOpen} {explainText} onclose={() => (explainOpen = false)} />
  <ResultCompareDialog open={compareOpen} currentResult={tab.result} onclose={() => (compareOpen = false)} />

  {#if resizing}
    <div class="fixed inset-0 z-50 cursor-row-resize"></div>
  {/if}
{/if}

// src/components/workspace/SqlTab.tsx
// src/components/workspace/SqlTab.tsx
import React, { useMemo, useState } from "react";
import { useDuckStore } from "@/store";
import SqlEditor from "@/components/editor/SqlEditor";
import { ResizablePanel, ResizablePanelGroup, ResizableHandle } from "@/components/ui/resizable";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import DuckUiTable from "@/components/table/DuckUItable";
import ChartVisualizationPro from "@/components/charts/ChartVisualizationPro";
import {
  FileX2,
  Table,
  BarChart3,
  AlertTriangle,
  Sparkles,
  Loader2,
  Scissors,
  LayoutDashboard,
  Pin,
  GitCompare,
  Map as MapIcon,
} from "lucide-react";
import GeoMapView from "@/components/map/GeoMapView";
import { findGeometryColumns } from "@/lib/geoResult";
import AddToDashboardDialog from "@/components/dashboard/AddToDashboardDialog";
import ResultCompareDialog from "@/components/workspace/ResultCompareDialog";
import { PIN_ROW_LIMIT } from "@/lib/resultDiff";
import QueryParamsBar from "@/components/editor/QueryParamsBar";
import { listParameterNames } from "@/lib/sqlParams";
import BrainResultActions from "@/components/duck-brain/BrainResultActions";
import { isNumericColumn } from "@/lib/chartDataTransform";
import { Alert, AlertTitle, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Skeleton } from "../ui/skeleton";
import { ErrorBoundary, FallbackProps } from "react-error-boundary";
import { toast } from "sonner";

const TableErrorFallback = ({ error, resetErrorBoundary }: FallbackProps) => (
  <div className="h-full flex items-center justify-center p-4">
    <div className="text-center max-w-md">
      <AlertTriangle className="mx-auto mb-4 text-destructive" size={32} />
      <h3 className="text-sm font-medium mb-2">Failed to render table</h3>
      <p className="text-xs text-muted-foreground mb-4">
        {error instanceof Error ? error.message : "An error occurred while displaying the results."}
      </p>
      <button
        onClick={resetErrorBoundary}
        className="text-xs px-3 py-1.5 bg-primary text-primary-foreground rounded hover:bg-primary/90"
      >
        Try again
      </button>
    </div>
  </div>
);

interface SqlTabProps {
  tabId: string;
}

const SqlTab: React.FC<SqlTabProps> = ({ tabId }) => {
  const tabs = useDuckStore((s) => s.tabs);
  const isExecuting = useDuckStore((s) => !!s.executingTabs[tabId]);
  const progress = useDuckStore((s) => s.queryProgress[tabId]);
  const cancelQuery = useDuckStore((s) => s.cancelQuery);
  const updateTabChartConfig = useDuckStore((s) => s.updateTabChartConfig);
  const generateSQL = useDuckStore((s) => s.generateSQL);
  const updateTabQuery = useDuckStore((s) => s.updateTabQuery);
  const [isFixing, setIsFixing] = useState(false);
  const [addToDashboardOpen, setAddToDashboardOpen] = useState(false);
  const [compareOpen, setCompareOpen] = useState(false);
  const pinResult = useDuckStore((s) => s.pinResult);
  const pinCount = useDuckStore((s) => s.resultPins.length);
  const currentTab = tabs.find((tab) => tab.id === tabId);
  const sqlText = useDuckStore((s) => {
    const content = s.tabs.find((tab) => tab.id === tabId)?.content;
    return typeof content === "string" ? content : "";
  });
  const paramNames = useMemo(() => listParameterNames(sqlText), [sqlText]);
  const [resultView, setResultView] = useState("table");
  // Cheap: a scan of the column types, not the rows.
  const geometryColumns = currentTab?.result ? findGeometryColumns(currentTab.result) : [];
  // A rerun without a GEOMETRY column drops the Map tab; fall back to the table.
  const activeView = resultView === "map" && geometryColumns.length === 0 ? "table" : resultView;

  const handleFixWithBrain = async () => {
    if (!currentTab || typeof currentTab.content !== "string" || !currentTab.result?.error) return;
    setIsFixing(true);
    try {
      const { buildFixQueryRequest } = await import("@/lib/duckBrain");
      const fixed = await generateSQL(
        buildFixQueryRequest(currentTab.content, currentTab.result.error)
      );
      if (fixed) {
        updateTabQuery(tabId, fixed);
        toast.success("Duck Brain suggested a fix — review it and run again");
      }
    } finally {
      setIsFixing(false);
    }
  };

  const handlePinResult = () => {
    if (!currentTab?.result || currentTab.result.error) return;
    const query = typeof currentTab.content === "string" ? currentTab.content : "";
    const pin = pinResult(tabId, query, currentTab.result);
    const { rows, sourceRowCount, truncated } = pin.snapshot;
    if (truncated) {
      toast.warning(
        `Pinned ${rows.length.toLocaleString()} of ${sourceRowCount.toLocaleString()} rows` +
          (rows.length >= PIN_ROW_LIMIT
            ? ` — pins keep at most ${PIN_ROW_LIMIT.toLocaleString()}`
            : " — the result itself was truncated")
      );
    } else {
      toast.success(`Pinned ${rows.length.toLocaleString()} rows for comparison`);
    }
  };

  const renderResults = () => {
    if (!currentTab || currentTab.type !== "sql") {
      return null;
    }

    // While the query runs, report what the engine has actually delivered so
    // far. The column headers arrive before the first row, so a long query
    // shows its real shape instead of a placeholder.
    if (isExecuting) {
      const headers = progress?.columns ?? [];
      return (
        <div className="h-full p-4 flex flex-col gap-4">
          <div className="flex items-center justify-between gap-4 flex-wrap">
            <div className="flex items-center gap-2 text-sm text-muted-foreground">
              <Loader2 className="h-4 w-4 animate-spin" />
              <span aria-live="polite">
                {progress && progress.rows > 0
                  ? `${progress.rows.toLocaleString()} rows so far`
                  : "Running query…"}
              </span>
              {progress && progress.elapsedMs > 1000 && (
                <span className="tabular-nums">· {(progress.elapsedMs / 1000).toFixed(1)}s</span>
              )}
            </div>
            <Button size="sm" variant="outline" onClick={() => cancelQuery(tabId)}>
              Stop
            </Button>
          </div>

          <div className="space-y-4">
            <div className="flex space-x-4">
              {headers.length > 0
                ? headers.slice(0, 15).map((name) => (
                    <div
                      key={name}
                      className="h-4 min-w-24 max-w-48 truncate text-xs font-medium text-muted-foreground"
                      title={name}
                    >
                      {name}
                    </div>
                  ))
                : Array.from({ length: 15 }).map((_, index) => (
                    <Skeleton key={`header-${index}`} className="h-4 w-32" />
                  ))}
            </div>

            <div className="space-y-2">
              {Array.from({ length: 22 }).map((_, rowIndex) => (
                <Skeleton key={`row-${rowIndex}`} className="flex space-x-4">
                  {Array.from({ length: 5 }).map((_, colIndex) => (
                    <div
                      key={`cell-${rowIndex}-${colIndex}`}
                      className="h-5 w-24 rounded-md animate-pulse"
                    />
                  ))}
                </Skeleton>
              ))}
            </div>
          </div>
        </div>
      );
    }

    // Show empty state if no query has been run
    if (!currentTab.result) {
      return (
        <div className="h-full flex items-center justify-center">
          <div className="flex flex-col items-center">
            <FileX2 size={48} className="text-muted-foreground mb-4" />
            <p className="text-sm text-muted-foreground">
              There's no data yet! Run a query to get started.
            </p>
          </div>
        </div>
      );
    }

    // Show error if query failed
    if (currentTab.result.error) {
      return (
        <div className="m-4 space-y-3">
          <Alert variant="destructive">
            <AlertTitle>Query Error</AlertTitle>
            <AlertDescription>{currentTab.result.error}</AlertDescription>
          </Alert>
          <Button size="sm" variant="outline" onClick={handleFixWithBrain} disabled={isFixing}>
            {isFixing ? (
              <Loader2 className="w-4 h-4 mr-2 animate-spin" />
            ) : (
              <Sparkles className="w-4 h-4 mr-2" />
            )}
            {isFixing ? "Duck Brain is thinking…" : "Fix with Duck Brain"}
          </Button>
        </div>
      );
    }

    // Show results in tabs (Table and Charts)
    return (
      <Tabs value={activeView} onValueChange={setResultView} className="h-full flex flex-col">
        {currentTab.result.truncated && (
          <div className="mx-4 mt-2 flex items-start gap-2 rounded-md border border-amber-500/40 bg-amber-500/10 px-3 py-2 text-xs">
            <Scissors className="mt-0.5 h-3.5 w-3.5 shrink-0 text-amber-500" />
            <span>
              Showing the first {currentTab.result.rowCount.toLocaleString()} rows. The query
              returns more — add a <code className="font-mono">LIMIT</code>, or raise the row limit
              in Settings. Parquet export still writes the complete result.
            </span>
          </div>
        )}
        <TabsContent value="table" className="flex-1 min-h-0 mt-0">
          <div className="h-full">
            <ErrorBoundary FallbackComponent={TableErrorFallback}>
              <DuckUiTable data={currentTab.result.data} />
            </ErrorBoundary>
          </div>
        </TabsContent>
        <TabsContent value="charts" className="flex-1 min-h-0 mt-0">
          <div className="h-full">
            <ChartVisualizationPro
              result={currentTab.result}
              chartConfig={currentTab.chartConfig}
              onConfigChange={(config) => updateTabChartConfig(tabId, config)}
            />
          </div>
        </TabsContent>
        {geometryColumns.length > 0 && (
          <TabsContent value="map" className="flex-1 min-h-0 mt-0">
            <GeoMapView result={currentTab.result} geometryColumns={geometryColumns} />
          </TabsContent>
        )}

        {/* Sits at the bottom, beside the paging controls, rather than as a
            full-width band above the results. The results panel is the part
            worth giving space to. */}
        <TabsList className="h-8 shrink-0 justify-start gap-1 rounded-none border-t bg-transparent px-4 py-0">
          <TabsTrigger value="table" className="h-6 gap-1.5 px-2 text-xs">
            <Table className="h-3.5 w-3.5" />
            Table
          </TabsTrigger>
          <TabsTrigger value="charts" className="h-6 gap-1.5 px-2 text-xs">
            <BarChart3 className="h-3.5 w-3.5" />
            Charts
          </TabsTrigger>
          {geometryColumns.length > 0 && (
            <TabsTrigger value="map" className="h-6 gap-1.5 px-2 text-xs">
              <MapIcon className="h-3.5 w-3.5" />
              Map
            </TabsTrigger>
          )}

          <div className="ml-auto" />
          {currentTab.result.data.length > 0 && (
            <BrainResultActions
              tabId={tabId}
              sql={typeof currentTab.content === "string" ? currentTab.content : ""}
              result={currentTab.result}
              onChartApplied={() => setResultView("charts")}
            />
          )}
          <Button
            size="sm"
            variant="ghost"
            className="h-6 gap-1.5 px-2 text-xs"
            onClick={handlePinResult}
            title="Keep a copy of this result to compare against later"
          >
            <Pin className="h-3.5 w-3.5" />
            Pin result
          </Button>
          <Button
            size="sm"
            variant="ghost"
            className="h-6 gap-1.5 px-2 text-xs"
            onClick={() => setCompareOpen(true)}
            disabled={pinCount === 0}
          >
            <GitCompare className="h-3.5 w-3.5" />
            Compare{pinCount > 0 ? ` (${pinCount})` : ""}
          </Button>
          <Button
            size="sm"
            variant="ghost"
            className="h-6 gap-1.5 px-2 text-xs"
            onClick={() => setAddToDashboardOpen(true)}
          >
            <LayoutDashboard className="h-3.5 w-3.5" />
            Add to dashboard
          </Button>
        </TabsList>
      </Tabs>
    );
  };

  if (!currentTab || currentTab.type !== "sql") {
    return null;
  }

  const currentSql = typeof currentTab.content === "string" ? currentTab.content : "";

  return (
    <div className="h-full">
      <AddToDashboardDialog
        open={addToDashboardOpen}
        onOpenChange={setAddToDashboardOpen}
        sql={currentSql}
        title={currentTab.title}
        chartConfig={currentTab.chartConfig}
        columns={currentTab.result?.columns.map((name) => ({
          name,
          numeric: isNumericColumn(currentTab.result?.data ?? [], name),
        }))}
      />
      {compareOpen && (
        <ResultCompareDialog
          open={compareOpen}
          onOpenChange={setCompareOpen}
          currentResult={currentTab.result}
        />
      )}
      <ResizablePanelGroup direction="horizontal">
        {/* Main Editor + Results Panel */}
        <ResizablePanel defaultSize={100} minSize={50}>
          <ResizablePanelGroup direction="vertical">
            <ResizablePanel defaultSize={50} minSize={25}>
              <SqlEditor tabId={tabId} title={currentTab.title} />
            </ResizablePanel>
            <ResizableHandle withHandle />
            <ResizablePanel defaultSize={50} minSize={25}>
              <div className="flex h-full flex-col">
                <QueryParamsBar tabId={tabId} names={paramNames} />
                <div className="min-h-0 flex-1">{renderResults()}</div>
              </div>
            </ResizablePanel>
          </ResizablePanelGroup>
        </ResizablePanel>
      </ResizablePanelGroup>
    </div>
  );
};

export default SqlTab;
