// src/lib/components/editor/ExportMenu.svelte
<script lang="ts">
  import { Download, FileText, Braces, Sheet as SheetIcon, Database, FolderDown } from 'lucide-svelte'
  import Button from '../common/Button.svelte'
  import ContextMenu, { type ContextMenuItem } from '../common/ContextMenu.svelte'
  import { duck } from '../../stores/duck.svelte'
  import { createTableExporters } from '@/lib/resultTable/tableExport'
  import type { DataRow } from '@/lib/resultTable/types'

  interface Props {
    /** Every row of the result, unfiltered. */
    rows: DataRow[]
    visibleColumns: string[]
    /** Rows after the grid's filters and sort, which is what gets exported. */
    filteredRows: () => DataRow[]
  }

  let { rows, visibleColumns, filteredRows }: Props = $props()

  const folders = $derived(duck((s) => s.mountedFolders))
  const canUseDuckDb = $derived(duck((s) => !!s.db && !!s.connection))

  let menu = $state<{ x: number; y: number } | null>(null)

  const items = $derived.by((): ContextMenuItem[] => {
    const exporters = createTableExporters(rows, {
      getVisibleColumnIds: () => visibleColumns,
      getFilteredRows: filteredRows,
    })
    const list: ContextMenuItem[] = [
      { id: 'csv', label: 'CSV', icon: FileText, onSelect: exporters.exportToCSV },
      { id: 'json', label: 'JSON', icon: Braces, onSelect: exporters.exportToJSON },
      { id: 'xlsx', label: 'Excel (XLSX)', icon: SheetIcon, onSelect: () => void exporters.exportToXLSX() },
      { id: 'parquet', label: 'Parquet', icon: Database, disabled: !canUseDuckDb, onSelect: () => void exporters.exportToDuckDB() },
    ]
    for (const folder of folders) {
      list.push(
        { id: `sep-${folder.id}`, separator: true },
        { id: `${folder.id}-csv`, label: `Save CSV to ${folder.name}`, icon: FolderDown, onSelect: () => void exporters.saveToFolderAsCSV(folder.id, folder.name) },
        { id: `${folder.id}-json`, label: `Save JSON to ${folder.name}`, icon: FolderDown, onSelect: () => void exporters.saveToFolderAsJSON(folder.id, folder.name) },
        { id: `${folder.id}-xlsx`, label: `Save XLSX to ${folder.name}`, icon: FolderDown, onSelect: () => void exporters.saveToFolderAsXLSX(folder.id, folder.name) },
        { id: `${folder.id}-parquet`, label: `Save Parquet to ${folder.name}`, icon: FolderDown, disabled: !canUseDuckDb, onSelect: () => void exporters.saveToFolderAsParquet(folder.id, folder.name) },
      )
    }
    return list
  })

  function toggle(e: MouseEvent) {
    if (menu) {
      menu = null
      return
    }
    const rect = (e.currentTarget as HTMLElement).getBoundingClientRect()
    menu = { x: rect.left, y: rect.top - 6 }
  }
</script>

<Button size="xs" variant="ghost" onclick={toggle} aria-expanded={menu !== null} disabled={rows.length === 0} title="Export the rows shown in the grid">
  <Download size={13} />
  Export
</Button>

<ContextMenu open={menu !== null} x={menu?.x ?? 0} y={menu?.y ?? 0} {items} onclose={() => (menu = null)} />

// src/components/table/duck-table/ExportMenu.tsx
import React from "react";
import {
  Download,
  ChevronDown,
  FolderOpen,
  FileSpreadsheet,
  FileJson,
  FileText,
  FileArchive,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
  DropdownMenuSub,
  DropdownMenuSubTrigger,
  DropdownMenuSubContent,
  DropdownMenuSeparator,
} from "@/components/ui/dropdown-menu";
import { useDuckStore } from "@/store";
import type { TableExporters } from "./tableExport";
import type { DataRow } from "./types";

interface ExportMenuProps extends TableExporters {
  data: DataRow[];
}

/** Export dropdown: downloads plus "Save to Folder" for mounted folders. */
const ExportMenu: React.FC<ExportMenuProps> = ({
  data,
  exportToCSV,
  exportToJSON,
  exportToXLSX,
  exportToDuckDB,
  saveToFolderAsCSV,
  saveToFolderAsJSON,
  saveToFolderAsXLSX,
  saveToFolderAsParquet,
}) => {
  // Get mounted folders from store
  const mountedFolders = useDuckStore((state) => state.mountedFolders);

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button
          variant="outline"
          size="sm"
          className="h-8 text-xs"
          disabled={!data || !data.length}
          title="Export data in various formats"
        >
          <Download className="mr-1 h-3.5 w-3.5" />
          Export
          <ChevronDown className="ml-1 h-3 w-3" />
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem onClick={exportToCSV}>
          <Download className="mr-2 h-3.5 w-3.5" />
          Export as CSV
        </DropdownMenuItem>
        <DropdownMenuItem onClick={exportToJSON}>
          <Download className="mr-2 h-3.5 w-3.5" />
          Export as JSON
        </DropdownMenuItem>
        <DropdownMenuItem onClick={exportToXLSX}>
          <Download className="mr-2 h-3.5 w-3.5" />
          Export as Excel (XLSX)
        </DropdownMenuItem>
        <DropdownMenuItem onClick={exportToDuckDB}>
          <Download className="mr-2 h-3.5 w-3.5" />
          Export as Parquet
        </DropdownMenuItem>

        {/* Save to Folder submenu */}
        {mountedFolders.length > 0 && (
          <>
            <DropdownMenuSeparator />
            <DropdownMenuSub>
              <DropdownMenuSubTrigger>
                <FolderOpen className="mr-2 h-3.5 w-3.5" />
                Save to Folder
              </DropdownMenuSubTrigger>
              <DropdownMenuSubContent>
                {mountedFolders.map((folder) => (
                  <DropdownMenuSub key={folder.id}>
                    <DropdownMenuSubTrigger>
                      <FolderOpen className="mr-2 h-3.5 w-3.5" />
                      {folder.name}
                    </DropdownMenuSubTrigger>
                    <DropdownMenuSubContent>
                      <DropdownMenuItem onClick={() => saveToFolderAsCSV(folder.id, folder.name)}>
                        <FileText className="mr-2 h-3.5 w-3.5" />
                        Save as CSV
                      </DropdownMenuItem>
                      <DropdownMenuItem onClick={() => saveToFolderAsJSON(folder.id, folder.name)}>
                        <FileJson className="mr-2 h-3.5 w-3.5" />
                        Save as JSON
                      </DropdownMenuItem>
                      <DropdownMenuItem onClick={() => saveToFolderAsXLSX(folder.id, folder.name)}>
                        <FileSpreadsheet className="mr-2 h-3.5 w-3.5" />
                        Save as Excel (XLSX)
                      </DropdownMenuItem>
                      <DropdownMenuItem
                        onClick={() => saveToFolderAsParquet(folder.id, folder.name)}
                      >
                        <FileArchive className="mr-2 h-3.5 w-3.5" />
                        Save as Parquet
                      </DropdownMenuItem>
                    </DropdownMenuSubContent>
                  </DropdownMenuSub>
                ))}
              </DropdownMenuSubContent>
            </DropdownMenuSub>
          </>
        )}
      </DropdownMenuContent>
    </DropdownMenu>
  );
};

export default ExportMenu;
