// src/components/workspace/ExtensionsSettings.tsx
import { useCallback, useEffect, useMemo, useState } from "react";
import { useDuckStore } from "@/store";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Download, Loader2, Play, Puzzle, RefreshCw } from "lucide-react";
import { toast } from "sonner";
import {
  isUnavailableExtensionError,
  type ExtensionAction,
  type ExtensionInfo,
} from "@/lib/duckdbExtensions";

/**
 * Extension manager, as a Settings section. Lists `duckdb_extensions()` for
 * the active connection and runs INSTALL / LOAD through the store.
 *
 * DuckDB has no column for "exists for this platform", so availability is
 * learned rather than hardcoded: an extension whose INSTALL/LOAD comes back
 * as a missing binary is marked unavailable for the rest of this visit.
 */
export default function ExtensionsSettings() {
  const fetchExtensions = useDuckStore((s) => s.fetchExtensions);
  const runExtensionAction = useDuckStore((s) => s.runExtensionAction);
  const session = useDuckStore((s) => s.currentSession);
  const connectionName = useDuckStore((s) => s.currentConnection?.name);

  const [extensions, setExtensions] = useState<ExtensionInfo[] | null>(null);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [isRefreshing, setIsRefreshing] = useState(false);
  const [pending, setPending] = useState<Record<string, ExtensionAction>>({});
  const [unavailable, setUnavailable] = useState<Set<string>>(() => new Set());
  const [filter, setFilter] = useState("");

  const readOnly = !!session?.capabilities.readonly;
  const isRemote = !!session?.capabilities.remote;

  const refresh = useCallback(async () => {
    setIsRefreshing(true);
    try {
      setExtensions(await fetchExtensions());
      setLoadError(null);
    } catch (error) {
      setLoadError(error instanceof Error ? error.message : "Failed to list extensions");
    } finally {
      setIsRefreshing(false);
    }
  }, [fetchExtensions]);

  useEffect(() => {
    let cancelled = false;
    fetchExtensions()
      .then((list) => {
        if (!cancelled) setExtensions(list);
      })
      .catch((error: unknown) => {
        if (!cancelled) {
          setLoadError(error instanceof Error ? error.message : "Failed to list extensions");
        }
      });
    return () => {
      cancelled = true;
    };
  }, [fetchExtensions]);

  const handleAction = async (action: ExtensionAction, name: string) => {
    setPending((p) => ({ ...p, [name]: action }));
    try {
      await runExtensionAction(action, name);
      toast.success(`${action === "install" ? "Installed" : "Loaded"} ${name}`);
      setUnavailable((prev) => {
        if (!prev.has(name)) return prev;
        const next = new Set(prev);
        next.delete(name);
        return next;
      });
    } catch (error) {
      const message = error instanceof Error ? error.message : "Unknown error";
      if (isUnavailableExtensionError(message)) {
        setUnavailable((prev) => new Set(prev).add(name));
      }
      toast.error(`Failed to ${action} ${name}`, { description: message });
    } finally {
      setPending((p) => {
        const next = { ...p };
        delete next[name];
        return next;
      });
      await refresh();
    }
  };

  const visible = useMemo(() => {
    const needle = filter.trim().toLowerCase();
    if (!extensions) return [];
    if (!needle) return extensions;
    return extensions.filter(
      (e) => e.name.toLowerCase().includes(needle) || e.description.toLowerCase().includes(needle)
    );
  }, [extensions, filter]);

  return (
    <div className="space-y-4">
      <div className="flex items-start justify-between gap-4">
        <div className="space-y-1">
          <h3 className="text-sm font-medium flex items-center gap-2">
            <Puzzle className="h-4 w-4" />
            DuckDB extensions
          </h3>
          <p className="text-xs text-muted-foreground">
            Extensions available to{" "}
            <span className="font-medium">{connectionName ?? "the active connection"}</span>.
            {isRemote
              ? " They install on the remote server."
              : " In the browser they download from extensions.duckdb.org, so installing needs a network connection the first time. Not every extension is built for WASM."}
          </p>
        </div>
        <Button
          variant="outline"
          size="sm"
          onClick={refresh}
          disabled={isRefreshing}
          aria-label="Refresh extension list"
        >
          <RefreshCw className={`h-4 w-4 ${isRefreshing ? "animate-spin" : ""}`} />
        </Button>
      </div>

      {readOnly && (
        <Alert>
          <AlertDescription className="text-xs">
            This connection is read-only, so extensions can be listed but not installed or loaded.
          </AlertDescription>
        </Alert>
      )}

      {loadError && (
        <Alert variant="destructive">
          <AlertDescription className="text-xs">{loadError}</AlertDescription>
        </Alert>
      )}

      {extensions === null && !loadError ? (
        <div className="flex items-center gap-2 text-sm text-muted-foreground">
          <Loader2 className="h-4 w-4 animate-spin" />
          Loading extensions…
        </div>
      ) : (
        extensions && (
          <>
            <Input
              placeholder="Filter extensions…"
              value={filter}
              onChange={(e) => setFilter(e.target.value)}
              className="h-8 text-sm"
            />
            <div className="divide-y rounded-md border">
              {visible.map((ext) => {
                const busy = pending[ext.name];
                const isUnavailable = unavailable.has(ext.name);
                return (
                  <div key={ext.name} className="flex items-center gap-3 px-3 py-2">
                    <div className="min-w-0 flex-1">
                      <div className="flex flex-wrap items-center gap-1.5">
                        <span className="font-mono text-sm">{ext.name}</span>
                        {ext.loaded && <Badge className="text-[10px] px-1.5 py-0">Loaded</Badge>}
                        {ext.installed && !ext.loaded && (
                          <Badge variant="secondary" className="text-[10px] px-1.5 py-0">
                            Installed
                          </Badge>
                        )}
                        {isUnavailable && (
                          <Badge
                            variant="outline"
                            className="text-[10px] px-1.5 py-0 text-amber-600 dark:text-amber-400"
                            title="The extension repository has no build of this extension for this platform"
                          >
                            {isRemote ? "Unavailable" : "Not available in WASM"}
                          </Badge>
                        )}
                      </div>
                      {ext.description && (
                        <p
                          className="text-xs text-muted-foreground truncate"
                          title={ext.description}
                        >
                          {ext.description}
                        </p>
                      )}
                    </div>
                    <div className="flex shrink-0 gap-1.5">
                      {!ext.installed && (
                        <Button
                          size="sm"
                          variant="outline"
                          className="h-7 px-2 text-xs"
                          disabled={readOnly || !!busy}
                          onClick={() => handleAction("install", ext.name)}
                        >
                          {busy === "install" ? (
                            <Loader2 className="h-3.5 w-3.5 mr-1 animate-spin" />
                          ) : (
                            <Download className="h-3.5 w-3.5 mr-1" />
                          )}
                          Install
                        </Button>
                      )}
                      {!ext.loaded && (
                        <Button
                          size="sm"
                          variant="outline"
                          className="h-7 px-2 text-xs"
                          disabled={readOnly || !!busy}
                          onClick={() => handleAction("load", ext.name)}
                        >
                          {busy === "load" ? (
                            <Loader2 className="h-3.5 w-3.5 mr-1 animate-spin" />
                          ) : (
                            <Play className="h-3.5 w-3.5 mr-1" />
                          )}
                          Load
                        </Button>
                      )}
                    </div>
                  </div>
                );
              })}
              {visible.length === 0 && (
                <p className="px-3 py-4 text-center text-xs text-muted-foreground">
                  No extensions match “{filter}”.
                </p>
              )}
            </div>
          </>
        )
      )}
    </div>
  );
}

// src/lib/components/settings/ExtensionsSettings.svelte
<script lang="ts">
  import { Download, Play, Puzzle, RefreshCw } from 'lucide-svelte'
  import { isUnavailableExtensionError, type ExtensionAction, type ExtensionInfo } from '@/lib/duckdbExtensions'
  import Badge from '../common/Badge.svelte'
  import Button from '../common/Button.svelte'
  import Input from '../common/Input.svelte'
  import Spinner from '../common/Spinner.svelte'
  import { duck, duckActions } from '../../stores/duck.svelte'
  import * as toast from '../../stores/toast.svelte'

  /*
    Extension manager, as a Settings section. Lists `duckdb_extensions()` for
    the active connection and runs INSTALL / LOAD through the store.

    DuckDB has no column for "exists for this platform", so availability is
    learned rather than hardcoded: an extension whose INSTALL/LOAD comes back
    as a missing binary is marked unavailable for the rest of this visit.
  */

  const readOnly = $derived(duck((s) => !!s.currentSession?.capabilities.readonly))
  const isRemote = $derived(duck((s) => !!s.currentSession?.capabilities.remote))
  const connectionName = $derived(duck((s) => s.currentConnection?.name))

  let extensions = $state.raw<ExtensionInfo[] | null>(null)
  let loadError = $state<string | null>(null)
  let refreshing = $state(false)
  let pending = $state<Record<string, ExtensionAction>>({})
  let unavailable = $state<Record<string, boolean>>({})
  let filter = $state('')

  const visible = $derived.by(() => {
    const needle = filter.trim().toLowerCase()
    if (!extensions) return []
    if (!needle) return extensions
    return extensions.filter(
      (e) => e.name.toLowerCase().includes(needle) || e.description.toLowerCase().includes(needle),
    )
  })

  async function refresh() {
    refreshing = true
    try {
      extensions = await duckActions().fetchExtensions()
      loadError = null
    } catch (error) {
      loadError = error instanceof Error ? error.message : 'Failed to list extensions'
    } finally {
      refreshing = false
    }
  }

  // The parent remounts this component per connection, so loading once on
  // mount is enough.
  $effect(() => {
    let cancelled = false
    duckActions()
      .fetchExtensions()
      .then((list) => {
        if (!cancelled) extensions = list
      })
      .catch((error: unknown) => {
        if (!cancelled) loadError = error instanceof Error ? error.message : 'Failed to list extensions'
      })
    return () => {
      cancelled = true
    }
  })

  async function run(action: ExtensionAction, name: string) {
    pending[name] = action
    try {
      await duckActions().runExtensionAction(action, name)
      toast.success(`${action === 'install' ? 'Installed' : 'Loaded'} ${name}`)
      delete unavailable[name]
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Unknown error'
      if (isUnavailableExtensionError(message)) unavailable[name] = true
      toast.error(`Failed to ${action} ${name}`, { description: message })
    } finally {
      delete pending[name]
      await refresh()
    }
  }
</script>

<div class="flex flex-col gap-4">
  <div class="flex items-start justify-between gap-4">
    <div class="min-w-0">
      <h2 class="flex items-center gap-2 text-[13px] font-semibold text-fg">
        <Puzzle size={14} class="text-fg-3" />
        DuckDB extensions
      </h2>
      <p class="mt-0.5 max-w-[64ch] text-xs leading-relaxed text-fg-3">
        Extensions available to
        <span class="font-medium text-fg-2">{connectionName ?? 'the active connection'}</span>.
        {isRemote
          ? 'They install on the remote server.'
          : 'In the browser they download from extensions.duckdb.org, so installing needs a network connection the first time. Not every extension is built for WASM.'}
      </p>
    </div>
    <Button icon size="sm" variant="outline" disabled={refreshing} aria-label="Refresh extension list" onclick={refresh}>
      <RefreshCw size={14} class={refreshing ? 'animate-spin' : ''} />
    </Button>
  </div>

  {#if readOnly}
    <p class="rounded-md bg-surface-2 px-3 py-2 text-xs text-fg-2">
      This connection is read-only, so extensions can be listed but not installed or loaded.
    </p>
  {/if}

  {#if loadError}
    <p class="rounded-md bg-danger-soft px-3 py-2 text-xs text-danger" role="alert">{loadError}</p>
  {/if}

  {#if extensions === null && !loadError}
    <div class="flex items-center gap-2 text-[13px] text-fg-3">
      <Spinner size="sm" />
      Loading extensions...
    </div>
  {:else if extensions}
    <label class="sr-only" for="extension-filter">Filter extensions</label>
    <Input id="extension-filter" type="search" size="sm" bind:value={filter} placeholder="Filter extensions..." />
    <ul class="divide-y divide-edge-subtle rounded-md border border-edge-subtle bg-surface">
      {#each visible as ext (ext.name)}
        {@const busy = pending[ext.name]}
        <li class="flex items-center gap-3 px-3 py-2">
          <div class="min-w-0 flex-1">
            <div class="flex flex-wrap items-center gap-1.5">
              <span class="font-mono text-[13px] text-fg">{ext.name}</span>
              {#if ext.loaded}
                <Badge tone="brand">Loaded</Badge>
              {:else if ext.installed}
                <Badge>Installed</Badge>
              {/if}
              {#if unavailable[ext.name]}
                <Badge tone="warning" title="The extension repository has no build of this extension for this platform">
                  {isRemote ? 'Unavailable' : 'Not available in WASM'}
                </Badge>
              {/if}
            </div>
            {#if ext.description}
              <p class="truncate text-xs text-fg-3" title={ext.description}>{ext.description}</p>
            {/if}
          </div>
          <div class="flex shrink-0 gap-1.5">
            {#if !ext.installed}
              <Button
                size="sm"
                variant="outline"
                disabled={readOnly || !!busy}
                loading={busy === 'install'}
                onclick={() => run('install', ext.name)}
              >
                {#if busy !== 'install'}<Download size={13} />{/if}
                Install
              </Button>
            {/if}
            {#if !ext.loaded}
              <Button
                size="sm"
                variant="outline"
                disabled={readOnly || !!busy}
                loading={busy === 'load'}
                onclick={() => run('load', ext.name)}
              >
                {#if busy !== 'load'}<Play size={13} />{/if}
                Load
              </Button>
            {/if}
          </div>
        </li>
      {/each}
      {#if visible.length === 0}
        <li class="px-3 py-4 text-center text-xs text-fg-3">No extensions match "{filter}".</li>
      {/if}
    </ul>
  {/if}
</div>
