// src/lib/components/duck-brain/SchemaAutocomplete.svelte
<script lang="ts">
  import { Table2, Columns3 } from 'lucide-svelte'
  import type { SchemaSuggestion } from '@/lib/duckBrain/schemaSuggestions'

  interface Props {
    open: boolean
    suggestions: SchemaSuggestion[]
    activeIndex: number
    /** Id of the listbox, referenced by the textarea through aria-controls. */
    id: string
    onselect: (suggestion: SchemaSuggestion) => void
  }

  let { open, suggestions, activeIndex, id, onselect }: Props = $props()

  let list = $state<HTMLDivElement | null>(null)

  // Keep the keyboard-highlighted item visible while arrowing through the list.
  $effect(() => {
    if (!list || activeIndex < 0) return
    const item = list.children[activeIndex] as HTMLElement | undefined
    item?.scrollIntoView({ block: 'nearest' })
  })
</script>

{#if open && suggestions.length > 0}
  <div class="surface-card absolute bottom-full left-0 z-50 mb-1.5 w-64 overflow-hidden rounded-md">
    <div bind:this={list} {id} class="max-h-48 overflow-auto py-1" role="listbox" aria-label="Tables and columns">
      {#each suggestions as suggestion, index (`${suggestion.type}-${suggestion.fullPath}`)}
        <button
          type="button"
          id="{id}-{index}"
          role="option"
          aria-selected={index === activeIndex}
          class="flex w-full items-center gap-2 px-2.5 py-1.5 text-left text-[13px] hover:bg-hover
            {index === activeIndex ? 'bg-hover text-fg' : 'text-fg-2'}"
          onclick={() => onselect(suggestion)}
        >
          {#if suggestion.type === 'table'}
            <Table2 size={14} class="shrink-0 text-accent" />
          {:else}
            <Columns3 size={14} class="shrink-0 text-fg-3" />
          {/if}
          <span class="min-w-0 flex-1">
            <span class="block truncate font-medium">{suggestion.name}</span>
            {#if suggestion.type === 'table'}
              <span class="block text-[10px] text-fg-3">
                {suggestion.rowCount ? `${suggestion.rowCount.toLocaleString()} rows` : 'table'}
              </span>
            {:else if suggestion.columnType}
              <span class="block text-[10px] text-fg-3">{suggestion.columnType}</span>
            {/if}
          </span>
        </button>
      {/each}
    </div>
    <div class="border-t border-edge-subtle bg-surface-2 px-2.5 py-1.5 text-[10px] text-fg-3">
      <kbd class="rounded-sm bg-active px-1">↑↓</kbd> navigate
      <span class="mx-1.5">·</span>
      <kbd class="rounded-sm bg-active px-1">Tab</kbd> select
      <span class="mx-1.5">·</span>
      <kbd class="rounded-sm bg-active px-1">Esc</kbd> close
    </div>
  </div>
{/if}

// src/components/duck-brain/SchemaAutocomplete.tsx
import React, { useEffect, useRef } from "react";
import { Table2, Columns3 } from "lucide-react";
import { cn } from "@/lib/utils";
import type { SchemaSuggestion } from "@/lib/duckBrain/schemaSuggestions";

export type { SchemaSuggestion };

interface SchemaAutocompleteProps {
  isOpen: boolean;
  suggestions: SchemaSuggestion[];
  activeIndex: number;
  onSelect: (suggestion: SchemaSuggestion) => void;
  position: { top: number; left: number };
  className?: string;
}

const SchemaAutocomplete: React.FC<SchemaAutocompleteProps> = ({
  isOpen,
  suggestions,
  activeIndex,
  onSelect,
  position,
  className,
}) => {
  const listRef = useRef<HTMLDivElement>(null);

  // Scroll active item into view
  useEffect(() => {
    if (listRef.current && activeIndex >= 0) {
      const activeItem = listRef.current.children[activeIndex] as HTMLElement;
      activeItem?.scrollIntoView({ block: "nearest" });
    }
  }, [activeIndex]);

  if (!isOpen || suggestions.length === 0) {
    return null;
  }

  return (
    <div
      className={cn(
        "absolute z-50 w-64 max-h-48 overflow-auto",
        "bg-popover border rounded-md shadow-lg",
        className
      )}
      style={{ bottom: position.top, left: position.left }}
    >
      <div ref={listRef} className="py-1">
        {suggestions.map((suggestion, index) => (
          <button
            key={`${suggestion.type}-${suggestion.fullPath}`}
            type="button"
            onClick={() => onSelect(suggestion)}
            className={cn(
              "w-full px-3 py-1.5 text-left text-sm flex items-center gap-2",
              "hover:bg-accent",
              index === activeIndex && "bg-accent"
            )}
          >
            {suggestion.type === "table" ? (
              <Table2 className="h-3.5 w-3.5 text-primary flex-shrink-0" />
            ) : (
              <Columns3 className="h-3.5 w-3.5 text-muted-foreground flex-shrink-0" />
            )}
            <div className="flex-1 min-w-0">
              <span className="font-medium truncate block">{suggestion.name}</span>
              {suggestion.type === "table" && (
                <span className="text-[10px] text-muted-foreground">
                  {suggestion.rowCount ? `${suggestion.rowCount.toLocaleString()} rows` : "table"}
                </span>
              )}
              {suggestion.type === "column" && suggestion.columnType && (
                <span className="text-[10px] text-muted-foreground">{suggestion.columnType}</span>
              )}
            </div>
          </button>
        ))}
      </div>
      <div className="px-3 py-1.5 text-[10px] text-muted-foreground border-t bg-muted/30">
        <kbd className="px-1 rounded bg-muted">↑↓</kbd> navigate
        <span className="mx-1.5">·</span>
        <kbd className="px-1 rounded bg-muted">Tab</kbd> select
        <span className="mx-1.5">·</span>
        <kbd className="px-1 rounded bg-muted">Esc</kbd> close
      </div>
    </div>
  );
};

export default SchemaAutocomplete;
