// src/components/explorer/file-importer/FileDetails.tsx
import React, { useState, useMemo } from "react";
import { format } from "date-fns";
import { FileWarning, FileCheck, X, FileIcon, Calendar, HardDrive, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";
import { Progress } from "@/components/ui/progress";
import { z } from "zod";
import CsvOptionsPanel from "./CsvOptionsPanel";
import { formatFileSize, tableNameSchema } from "./helpers";
import type { CsvImportOptions, FileImportState, FileWithPreview } from "./types";

interface FileDetailsProps {
  file: FileWithPreview;
  tableName: string;
  onTableNameChange: (name: string) => void;
  status: FileImportState;
  onRemove: () => void;
  onRetry: () => void;
  csvOptions?: CsvImportOptions;
  onCsvOptionsChange?: (options: CsvImportOptions) => void;
}

const getFileIcon = (fileType: string) => {
  const iconProps = { className: "w-8 h-8" };
  switch (fileType.toLowerCase()) {
    case "csv":
      return <FileIcon {...iconProps} color="#38A169" />;
    case "json":
      return <FileIcon {...iconProps} color="#D69E2E" />;
    case "parquet":
      return <FileIcon {...iconProps} color="#3182CE" />;
    case "arrow":
      return <FileIcon {...iconProps} color="#805AD5" />;
    case "duckdb":
      return <FileIcon {...iconProps} color="#ED8936" />;
    case "xlsx":
      return <FileIcon {...iconProps} color="#4299E1" />;
    default:
      return <FileIcon {...iconProps} color="#718096" />;
  }
};

const FileDetails: React.FC<FileDetailsProps> = ({
  file,
  tableName,
  onTableNameChange,
  status,
  onRemove,
  onRetry,
  csvOptions,
  onCsvOptionsChange,
}) => {
  const [showAdvancedOptions, setShowAdvancedOptions] = useState(false);
  const fileType = file.name.split(".").pop()?.toLowerCase() || "";
  const lastModified = new Date(file.lastModified);
  const isCsvFile = fileType === "csv";

  const tableNameError = useMemo(() => {
    try {
      tableNameSchema.parse(tableName);
      return null;
    } catch (error) {
      return error instanceof z.ZodError ? error.issues[0].message : "Invalid table name";
    }
  }, [tableName]);

  // Handle CSV option changes
  const handleCsvOptionChange = (
    key: keyof CsvImportOptions,
    value: string | boolean | number | undefined
  ) => {
    if (onCsvOptionsChange && csvOptions) {
      onCsvOptionsChange({
        ...csvOptions,
        [key]: value,
      });
    }
  };

  return (
    <div className="rounded-lg border p-4 shadow-sm">
      <div className="flex items-start gap-4">
        <div className="flex-shrink-0">{getFileIcon(fileType)}</div>

        <div className="flex-grow space-y-3">
          <div className="flex items-start justify-between">
            <div>
              <h3 className="font-medium text-lg">{file.name}</h3>
              <div className="flex items-center gap-4 text-sm text-gray-600 mt-1">
                <TooltipProvider>
                  <Tooltip>
                    <TooltipTrigger className="flex items-center gap-1">
                      <HardDrive className="w-4 h-4" />
                      {formatFileSize(file.size)}
                    </TooltipTrigger>
                    <TooltipContent>File size</TooltipContent>
                  </Tooltip>
                </TooltipProvider>

                <TooltipProvider>
                  <Tooltip>
                    <TooltipTrigger className="flex items-center gap-1">
                      <Calendar className="w-4 h-4" />
                      {format(lastModified, "MMM dd, yyyy")}
                    </TooltipTrigger>
                    <TooltipContent>Last modified</TooltipContent>
                  </Tooltip>
                </TooltipProvider>

                <span className="uppercase px-2 py-0.5 rounded text-xs">{fileType}</span>
              </div>
            </div>
            <div className="flex items-center gap-2">
              {status.status === "error" && (
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={onRetry}
                  className="text-gray-500 hover:text-gray-700"
                  aria-label="Retry"
                >
                  <RefreshCw className="w-4 h-4" />
                </Button>
              )}
              <Button
                variant="ghost"
                size="sm"
                onClick={onRemove}
                className="text-gray-500 hover:text-gray-700"
                aria-label="Remove file"
              >
                <X className="w-4 h-4" />
              </Button>
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor={`table-${file.name}`}>Table Name</Label>
            <Input
              id={`table-${file.name}`}
              value={tableName}
              required
              onChange={(e) => onTableNameChange(e.target.value)}
              placeholder="Enter table name"
              className="max-w-md p-2 ml-1"
              disabled={status.status === "uploading" || status.status === "processing"}
            />
            {tableNameError && <p className="text-sm text-red-500">{tableNameError}</p>}
            <p className="text-sm text-gray-500">
              This name will be used to reference the table in SQL queries
            </p>
          </div>

          {/* CSV import options */}
          {isCsvFile && csvOptions && (
            <CsvOptionsPanel
              file={file}
              status={status}
              csvOptions={csvOptions}
              showAdvancedOptions={showAdvancedOptions}
              setShowAdvancedOptions={setShowAdvancedOptions}
              handleCsvOptionChange={handleCsvOptionChange}
            />
          )}

          {status.status === "uploading" && status.progress !== undefined && (
            <div className="flex flex-col space-y-2">
              <span className="text-sm text-gray-500">Uploading... {status.progress}%</span>
              <Progress value={status.progress} />
            </div>
          )}

          {status.status === "success" && (
            <div className="flex items-center gap-2 text-green-600 bg-green-50 p-2 rounded max-w-md ">
              <FileCheck className="w-4 h-4" />
              <span className="text-sm">Successfully imported</span>
            </div>
          )}

          {status.status === "error" && status.error && (
            <div className="flex items-center gap-2 text-red-600 bg-red-500/20 p-2 rounded max-w-md">
              <FileWarning className="w-4 h-4" />
              <span className="text-xs">{status.error}</span>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default FileDetails;

// src/lib/components/importer/FileDetails.svelte
<script lang="ts">
  import { FileWarning, FileCheck, X, File as FileIcon, Calendar, HardDrive, RefreshCw } from 'lucide-svelte'
  import Button from '../common/Button.svelte'
  import Input from '../common/Input.svelte'
  import FormField from '../common/FormField.svelte'
  import Badge from '../common/Badge.svelte'
  import CsvOptionsPanel from './CsvOptionsPanel.svelte'
  import { formatFileSize } from '@/lib/fileImporter/helpers'
  import { tableNameError } from '@/lib/fileImporter/context'
  import type { CsvImportOptions, FileImportState } from '@/lib/fileImporter/types'

  interface Props {
    file: File
    tableName: string
    ontablenamechange: (name: string) => void
    status: FileImportState
    onremove: () => void
    onretry: () => void
    csvOptions?: CsvImportOptions
    oncsvoptionschange?: (options: CsvImportOptions) => void
  }

  let { file, tableName, ontablenamechange, status, onremove, onretry, csvOptions, oncsvoptionschange }: Props = $props()

  const iconTones: Record<string, string> = {
    csv: 'text-success',
    json: 'text-warning',
    parquet: 'text-info',
    arrow: 'text-accent',
    duckdb: 'text-accent',
    xlsx: 'text-info',
  }

  const fileType = $derived(file.name.split('.').pop()?.toLowerCase() ?? '')
  const idSuffix = $derived(file.name.replace(/[^a-zA-Z0-9_-]/g, '-'))
  const busy = $derived(status.status === 'uploading' || status.status === 'processing')
  const nameError = $derived(tableNameError(tableName))
  const lastModified = $derived(
    new Date(file.lastModified).toLocaleDateString('en-US', { month: 'short', day: '2-digit', year: 'numeric' })
  )

  function changeCsvOption(key: keyof CsvImportOptions, value: string | boolean | number | undefined) {
    if (oncsvoptionschange && csvOptions) oncsvoptionschange({ ...csvOptions, [key]: value })
  }
</script>

<div class="rounded-md border border-edge bg-surface p-3">
  <div class="flex items-start gap-3">
    <FileIcon size={22} strokeWidth={1.5} class="mt-0.5 shrink-0 {iconTones[fileType] ?? 'text-fg-3'}" />

    <div class="min-w-0 flex-1">
      <div class="flex items-start justify-between gap-2">
        <div class="min-w-0">
          <h3 class="truncate text-[13px] font-medium text-fg" title={file.name}>{file.name}</h3>
          <div class="mt-1 flex flex-wrap items-center gap-3 text-xs text-fg-3">
            <span class="inline-flex items-center gap-1" title="File size">
              <HardDrive size={12} />
              {formatFileSize(file.size)}
            </span>
            <span class="inline-flex items-center gap-1" title="Last modified">
              <Calendar size={12} />
              {lastModified}
            </span>
            <Badge class="uppercase">{fileType}</Badge>
          </div>
        </div>
        <div class="flex shrink-0 items-center">
          {#if status.status === 'error'}
            <Button icon variant="ghost" size="xs" onclick={onretry} aria-label="Retry {file.name}" title="Retry">
              <RefreshCw size={13} />
            </Button>
          {/if}
          <Button icon variant="ghost" size="xs" onclick={onremove} aria-label="Remove {file.name}" title="Remove file">
            <X size={13} />
          </Button>
        </div>
      </div>

      <FormField
        class="mt-3"
        label="Table name"
        for="table-{idSuffix}"
        required
        error={nameError ?? undefined}
        hint="This name will be used to reference the table in SQL queries"
      >
        <Input
          id="table-{idSuffix}"
          size="sm"
          mono
          required
          value={tableName}
          placeholder="Enter table name"
          invalid={!!nameError}
          disabled={busy}
          oninput={(e) => ontablenamechange(e.currentTarget.value)}
        />
      </FormField>

      {#if fileType === 'csv' && csvOptions}
        <CsvOptionsPanel {idSuffix} disabled={busy} {csvOptions} onchange={changeCsvOption} />
      {/if}

      {#if status.status === 'uploading' && status.progress !== undefined}
        <div class="mt-3">
          <span class="text-xs text-fg-3">Uploading... {status.progress}%</span>
          <div
            class="mt-1 h-1.5 overflow-hidden rounded-full bg-surface-2"
            role="progressbar"
            aria-valuemin={0}
            aria-valuemax={100}
            aria-valuenow={status.progress}
            aria-label="Upload progress for {file.name}"
          >
            <div class="h-full bg-accent transition-[width]" style="width: {status.progress}%"></div>
          </div>
        </div>
      {/if}

      {#if status.status === 'success'}
        <p class="mt-3 flex items-center gap-1.5 rounded-md bg-success-soft px-2 py-1.5 text-xs text-success">
          <FileCheck size={13} />
          Successfully imported
        </p>
      {/if}

      {#if status.status === 'error' && status.error}
        <p class="mt-3 flex items-start gap-1.5 rounded-md bg-danger-soft px-2 py-1.5 text-xs text-danger" role="alert">
          <FileWarning size={13} class="mt-0.5 shrink-0" />
          <span class="min-w-0 break-words">{status.error}</span>
        </p>
      {/if}
    </div>
  </div>
</div>
