// src/components/explorer/file-importer/SchemaEditor.tsx
import React from "react";
import { ChevronDown, ChevronUp } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { DUCKDB_TYPES } from "./constants";
import type { SchemaColumn } from "./types";

export interface SchemaEditorProps {
  schemaColumns: SchemaColumn[];
  isSchemaCustomizing: boolean;
  setIsSchemaCustomizing: (customizing: boolean) => void;
  handleToggleColumn: (originalName: string) => void;
  handleRenameColumn: (originalName: string, newName: string) => void;
  handleChangeColumnType: (originalName: string, type: string) => void;
}

/** Column include/rename/type editor shown under the URL preview. */
const SchemaEditor: React.FC<SchemaEditorProps> = ({
  schemaColumns,
  isSchemaCustomizing,
  setIsSchemaCustomizing,
  handleToggleColumn,
  handleRenameColumn,
  handleChangeColumnType,
}) => {
  return (
    <Card>
      <CardContent className="p-4">
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <div>
              <h4 className="font-semibold text-base">Schema Customization</h4>
              <p className="text-sm text-muted-foreground">
                Customize column names, types, and visibility before importing
              </p>
            </div>
            <Button
              variant="ghost"
              size="sm"
              onClick={() => setIsSchemaCustomizing(!isSchemaCustomizing)}
            >
              {isSchemaCustomizing ? (
                <>
                  <ChevronUp className="w-4 h-4 mr-2" />
                  Hide
                </>
              ) : (
                <>
                  <ChevronDown className="w-4 h-4 mr-2" />
                  Customize
                </>
              )}
            </Button>
          </div>

          {isSchemaCustomizing && (
            <div className="border rounded-lg overflow-hidden">
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead className="bg-muted">
                    <tr>
                      <th className="p-2 text-left w-12">Include</th>
                      <th className="p-2 text-left">Original Name</th>
                      <th className="p-2 text-left">New Name</th>
                      <th className="p-2 text-left w-48">Type</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y">
                    {schemaColumns.map((col) => (
                      <tr key={col.originalName} className={!col.included ? "opacity-50" : ""}>
                        <td className="p-2">
                          <Checkbox
                            checked={col.included}
                            onCheckedChange={() => handleToggleColumn(col.originalName)}
                          />
                        </td>
                        <td className="p-2">
                          <code className="text-xs bg-muted px-2 py-1 rounded">
                            {col.originalName}
                          </code>
                        </td>
                        <td className="p-2">
                          <Input
                            value={col.newName}
                            onChange={(e) => handleRenameColumn(col.originalName, e.target.value)}
                            disabled={!col.included}
                            className="h-8 text-xs"
                            placeholder="Column name"
                          />
                        </td>
                        <td className="p-2">
                          <Select
                            value={col.type}
                            onValueChange={(value) =>
                              handleChangeColumnType(col.originalName, value)
                            }
                            disabled={!col.included}
                          >
                            <SelectTrigger className="h-8 text-xs">
                              <SelectValue />
                            </SelectTrigger>
                            <SelectContent>
                              {DUCKDB_TYPES.map((type) => (
                                <SelectItem key={type} value={type} className="text-xs">
                                  {type}
                                </SelectItem>
                              ))}
                            </SelectContent>
                          </Select>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              <div className="p-3 bg-muted/50 text-xs text-muted-foreground">
                <p>
                  {schemaColumns.filter((col) => col.included).length} of {schemaColumns.length}{" "}
                  columns will be imported
                </p>
              </div>
            </div>
          )}
        </div>
      </CardContent>
    </Card>
  );
};

export default SchemaEditor;

// src/lib/components/importer/SchemaEditor.svelte
<script lang="ts">
  import { ChevronDown, ChevronUp } from 'lucide-svelte'
  import Button from '../common/Button.svelte'
  import Input from '../common/Input.svelte'
  import Select from '../common/Select.svelte'
  import { DUCKDB_TYPES } from '@/lib/fileImporter/constants'
  import type { UrlImport } from '@/lib/fileImporter/urlImport.svelte'

  interface Props {
    url: UrlImport
  }

  let { url }: Props = $props()

  const includedCount = $derived(url.schemaColumns.filter((col) => col.included).length)

  // The sniffer reports types outside the short list (HUGEINT, VARCHAR[], ...).
  // Without its own option the select would show a blank value.
  function typeOptions(current: string) {
    const known = DUCKDB_TYPES.map((type) => ({ value: type as string, label: type as string }))
    return known.some((option) => option.value === current) ? known : [{ value: current, label: current }, ...known]
  }
</script>

<!-- Column include/rename/type editor shown under the URL preview. -->
<div class="rounded-md border border-edge bg-surface p-3">
  <div class="flex items-center justify-between gap-3">
    <div>
      <h4 class="text-[13px] font-semibold text-fg">Schema customization</h4>
      <p class="text-xs text-fg-3">Customize column names, types, and visibility before importing</p>
    </div>
    <Button
      variant="ghost"
      size="sm"
      aria-expanded={url.isSchemaCustomizing}
      onclick={() => (url.isSchemaCustomizing = !url.isSchemaCustomizing)}
    >
      {#if url.isSchemaCustomizing}
        <ChevronUp size={14} />
        Hide
      {:else}
        <ChevronDown size={14} />
        Customize
      {/if}
    </Button>
  </div>

  {#if url.isSchemaCustomizing}
    <div class="mt-3 overflow-hidden rounded-md border border-edge-subtle">
      <div class="ds-table-wrap">
        <table class="ds-table">
          <thead>
            <tr class="ds-table-head-row">
              <th class="ds-table-th-compact w-14">Include</th>
              <th class="ds-table-th-compact">Original name</th>
              <th class="ds-table-th-compact">New name</th>
              <th class="ds-table-th-compact w-44">Type</th>
            </tr>
          </thead>
          <tbody>
            {#each url.schemaColumns as col (col.originalName)}
              <tr class="ds-table-row-static {col.included ? '' : 'opacity-50'}">
                <td class="ds-td-compact">
                  <input
                    type="checkbox"
                    class="ds-checkbox ds-checkbox-sm"
                    checked={col.included}
                    aria-label="Include {col.originalName}"
                    onchange={() => url.handleToggleColumn(col.originalName)}
                  />
                </td>
                <td class="ds-td-compact">
                  <code class="rounded-sm bg-surface-2 px-1.5 py-0.5 font-mono text-[11px]">{col.originalName}</code>
                </td>
                <td class="ds-td-compact">
                  <Input
                    size="sm"
                    mono
                    value={col.newName}
                    placeholder="Column name"
                    disabled={!col.included}
                    oninput={(e) => url.handleRenameColumn(col.originalName, e.currentTarget.value)}
                  />
                </td>
                <td class="ds-td-compact">
                  <Select
                    size="sm"
                    value={col.type}
                    options={typeOptions(col.type)}
                    disabled={!col.included}
                    onchange={(value) => url.handleChangeColumnType(col.originalName, value)}
                  />
                </td>
              </tr>
            {/each}
          </tbody>
        </table>
      </div>
      <p class="bg-surface-2 px-3 py-2 text-xs text-fg-3">
        {includedCount} of {url.schemaColumns.length} columns will be imported
      </p>
    </div>
  {/if}
</div>
