// src/lib/components/dashboard/DashboardTab.svelte
<script lang="ts">
  import { onDestroy, untrack } from 'svelte'
  import { createSubscriber } from 'svelte/reactivity'
  import type { Extension } from '@codemirror/state'
  import { Copy, Eye, Pencil, RefreshCw, Share2, Timer } from 'lucide-svelte'
  import Button from '../common/Button.svelte'
  import Input from '../common/Input.svelte'
  import Select from '../common/Select.svelte'
  import { duck, duckActions } from '../../stores/duck.svelte'
  import { datasetsFor, getDashboardInputs, getDashboardRunner } from '@/store/slices/dashboardSlice'
  import { datasetCacheKey, type DatasetResult } from '@/services/dashboard/queryRunner'
  import { parseDashboardSource } from '@/services/dashboard/markdown'
  import type { InputValue } from '@/services/dashboard/inputs'
  import {
    decideRefresh,
    formatRefreshInterval,
    formatRelativeTime,
    latestFetchedAt,
    parseRefreshParam,
    REFRESH_INTERVAL_OPTIONS,
  } from '@/services/dashboard/refresh'
  import DashboardSourceEditor from './DashboardSourceEditor.svelte'
  import { collaborativeBinding } from '@/lib/editor/collaboration'
  import { getCollaboration } from '@/store/slices/sessionSlice'
  import MarkdownDashboard from './MarkdownDashboard.svelte'
  import ShareDashboardDialog from './ShareDashboardDialog.svelte'

  /**
   * A dashboard document, as a workspace tab.
   *
   * View renders the document like a report. Edit is a split pane: markdown
   * source on the left, the live document on the right, re-rendered as you type.
   * The source is what persists and what a live session shares. The document IS
   * the dashboard.
   */
  interface Props {
    tabId: string
    /** Opens the workspace level Share Live flow from the share sheet. */
    onsharelive?: () => void
  }

  let { tabId, onsharelive }: Props = $props()

  const uid = $props.id()

  const SAVE_DEBOUNCE_MS = 600
  const SPLIT_KEY = 'duck-ui-dashboard-split-percent'
  const MIN_SPLIT = 25
  const MAX_SPLIT = 75

  /** Shared empty snapshots, so an unknown dashboard reads as stable values. */
  const EMPTY_RESULTS: ReadonlyMap<string, DatasetResult> = new Map()
  const EMPTY_INPUTS: ReadonlyMap<string, InputValue> = new Map()

  const tab = $derived(duck((s) => s.tabs.find((entry) => entry.id === tabId)))
  const dashboardId = $derived(typeof tab?.content === 'string' ? tab.content : '')
  const dashboard = $derived(duck((s) => s.dashboards.find((entry) => entry.id === dashboardId)))
  const isEditing = $derived(duck((s) => s.isDashboardEditing))
  const engineReady = $derived(duck((s) => s.isInitialized))
  const canEdit = $derived(dashboard?.role !== 'viewer')

  let refreshing = $state(false)
  let shareOpen = $state(false)
  // The draft leads while typing; the store catches up on a debounce. Null
  // means "no local edits pending" and the stored source is authoritative.
  let draft = $state<string | null>(null)
  const source = $derived(draft ?? dashboard?.source ?? '')
  const parsed = $derived(parseDashboardSource(source))
  const hasQueries = $derived(parsed.queries.length > 0)

  /**
   * In a live session the source editor is bound to the dashboard's shared
   * text. Registered on first edit in a session, so a dashboard opened
   * mid-session becomes co-editable too.
   */
  const sessionStatus = $derived(duck((s) => s.session.status))
  let collabExtensions = $state.raw<Extension[]>([])

  $effect(() => {
    const id = dashboardId
    if (sessionStatus !== 'connected' || !id || !isEditing) return
    const collaboration = getCollaboration()
    if (!collaboration) return

    const { name, text: initial } = untrack(() => ({ name: dashboard?.name ?? '', text: source }))
    collaboration.document.ensureDashboard(id, name, initial)
    const text = collaboration.document.dashboardText(id)
    if (!text) return

    collabExtensions = [collaborativeBinding({ text, presence: collaboration.presence, tabId: `dashboard:${tabId}` })]
    return () => {
      collabExtensions = []
    }
  })

  // Results come from the runner, not the store: a refresh must not push
  // every batch through a store subscription.
  const watchResults = $derived.by(() => {
    const id = dashboardId
    return id ? createSubscriber((update) => getDashboardRunner(id).onChange(() => update())) : null
  })
  const results = $derived.by(() => {
    if (!dashboardId || !watchResults) return EMPTY_RESULTS
    watchResults()
    return getDashboardRunner(dashboardId).snapshot()
  })

  // Input values, same pattern: view state living beside the runner.
  const inputs = $derived(dashboardId ? getDashboardInputs(dashboardId) : undefined)
  const watchInputs = $derived.by(() => {
    const store = inputs
    return store ? createSubscriber((update) => store.subscribe(update)) : null
  })
  const inputValues = $derived.by(() => {
    if (!inputs || !watchInputs) return EMPTY_INPUTS
    watchInputs()
    return inputs.snapshot()
  })

  // Debounced persistence of edits.
  let saveTimer: ReturnType<typeof setTimeout> | undefined
  let pendingSave: string | null = null
  let destroyed = false

  function persist() {
    clearTimeout(saveTimer)
    saveTimer = undefined
    const value = pendingSave
    pendingSave = null
    if (value === null) return
    const current = duckActions().dashboards.find((entry) => entry.id === dashboardId)
    if (current && current.source !== value) void duckActions().updateDashboard({ ...current, source: value })
    // The store has the text now. Letting go of the draft is what lets a
    // change from outside (Add to dashboard, a remote edit) show up here.
    if (draft === value) draft = null
  }

  function handleSourceChange(value: string) {
    pendingSave = value
    // The editor reports its last edits while it is being torn down. With
    // the tab itself closing there is no later, so save right away.
    if (destroyed) {
      persist()
      return
    }
    draft = value
    clearTimeout(saveTimer)
    saveTimer = setTimeout(persist, SAVE_DEBOUNCE_MS)
  }

  onDestroy(() => {
    destroyed = true
    persist()
  })

  // Run whatever the document declares, whenever the set of queries changes.
  // Keyed on name+sql: editing a query re-runs it, editing prose does not.
  // `engineReady` is a dependency for the reload path: a restored dashboard
  // tab renders BEFORE the WASM engine finishes booting, so the first run
  // fails with "connection not available", and without re-running when the
  // engine arrives, it would stay failed forever.
  const querySignature = $derived(parsed.queries.map((query) => `${query.name}:${query.sql}`).join(' '))
  const hasDashboard = $derived(dashboard !== undefined)
  const lastRunKeys = new Map<string, string>()
  $effect(() => {
    const values = inputValues
    const id = dashboardId
    if (!engineReady || !id || !hasDashboard || querySignature === '') return
    untrack(() => {
      if (!dashboard) return
      const runner = getDashboardRunner(id)
      // Only datasets whose FINAL SQL changed re-run. Turning a date picker must
      // re-run the queries that reference it and leave the rest untouched.
      for (const dataset of datasetsFor({ ...dashboard, source }, values)) {
        const key = datasetCacheKey(dataset)
        if (lastRunKeys.get(dataset.id) === key) continue
        lastRunKeys.set(dataset.id, key)
        void runner.run(dataset)
      }
    })
  })

  // Auto-refresh
  // `?refresh=<seconds>` on the page URL is a kiosk override: it applies to
  // every dashboard opened in this page load and is never persisted. Picking
  // an interval in the toolbar drops the override and saves the choice.
  let urlRefresh = $state(parseRefreshParam(window.location.search))
  const intervalSeconds = $derived(
    !hasQueries || !engineReady ? 0 : (urlRefresh ?? dashboard?.refreshIntervalSeconds ?? 0),
  )

  let hidden = $state(document.visibilityState === 'hidden')
  $effect(() => {
    const onVisibility = () => (hidden = document.visibilityState === 'hidden')
    document.addEventListener('visibilitychange', onVisibility)
    return () => document.removeEventListener('visibilitychange', onVisibility)
  })

  const anyLoading = $derived([...results.values()].some((result) => result.status === 'loading'))
  const inFlight = $derived(refreshing || anyLoading)
  // Completed-refresh time, including ones where every query failed (those
  // carry no fetchedAt, but still count as "we tried" for scheduling).
  let lastAttemptAt = $state<number | null>(null)
  const lastFetchedAt = $derived(latestFetchedAt(results.values()))
  const lastRefreshedAt = $derived(
    lastAttemptAt === null
      ? lastFetchedAt
      : lastFetchedAt === null
        ? lastAttemptAt
        : Math.max(lastAttemptAt, lastFetchedAt),
  )

  async function refreshAll() {
    if (!dashboardId || refreshing) return
    refreshing = true
    try {
      await duckActions().runDashboard(dashboardId, true)
    } finally {
      refreshing = false
      lastAttemptAt = Date.now()
    }
  }

  // One timer at a time, re-armed whenever any input to the decision changes.
  // `wake` bumps when a wait elapses so the decision is re-evaluated.
  let wake = $state(0)
  $effect(() => {
    void wake
    const decision = decideRefresh({
      intervalSeconds,
      // Enabling the interval before anything has loaded anchors on "now".
      lastRefreshedAt,
      now: Date.now(),
      hidden,
      inFlight,
    })
    if (decision.action === 'idle') return
    const timer = setTimeout(
      () => {
        if (decision.action === 'refresh') void refreshAll()
        else wake += 1
      },
      decision.action === 'refresh' ? 0 : decision.delayMs,
    )
    return () => clearTimeout(timer)
  })

  // Anchor the first scheduled run when the interval turns on with nothing
  // loaded yet, so it fires one interval later rather than never.
  $effect(() => {
    if (intervalSeconds <= 0 || lastRefreshedAt !== null) return
    const timer = setTimeout(() => (lastAttemptAt = Date.now()), 0)
    return () => clearTimeout(timer)
  })

  // Keeps the "updated ... ago" label moving without re-rendering per second.
  let now = $state(Date.now())
  $effect(() => {
    if (lastRefreshedAt === null) return
    const update = () => (now = Date.now())
    const timer = setInterval(update, 15_000)
    const initial = setTimeout(update, 0)
    return () => {
      clearInterval(timer)
      clearTimeout(initial)
    }
  })

  const selectedInterval = $derived(urlRefresh ?? dashboard?.refreshIntervalSeconds ?? 0)
  const intervalOptions = $derived(
    // An interval from a link may not be one of the presets.
    (REFRESH_INTERVAL_OPTIONS.some((option) => option.seconds === selectedInterval)
      ? REFRESH_INTERVAL_OPTIONS
      : [...REFRESH_INTERVAL_OPTIONS, { seconds: selectedInterval, label: '' }]
    ).map((option) => ({
      value: String(option.seconds),
      label: option.seconds === 0 ? 'Auto-refresh off' : `Every ${formatRefreshInterval(option.seconds)}`,
    })),
  )

  function handleIntervalChange(value: string) {
    if (!dashboard) return
    urlRefresh = null
    const seconds = Number(value)
    void duckActions().updateDashboard({
      ...dashboard,
      refreshIntervalSeconds: seconds > 0 ? seconds : undefined,
    })
  }

  function rename(name: string) {
    if (dashboard) void duckActions().updateDashboard({ ...dashboard, name })
  }

  async function saveEditableCopy() {
    if (!dashboard) return
    const copy = await duckActions().duplicateDashboard(dashboard.id)
    if (copy) duckActions().openDashboardTab(copy.id, copy.name)
  }

  // Split pane
  let splitEl: HTMLDivElement | undefined = $state()
  let resizing = $state(false)
  const savedSplit = parseFloat(localStorage.getItem(SPLIT_KEY) ?? '')
  let splitPercent = $state(Number.isNaN(savedSplit) ? 50 : savedSplit)

  function clampSplit(value: number): number {
    return Math.max(MIN_SPLIT, Math.min(MAX_SPLIT, value))
  }

  function onResizeStart(e: MouseEvent) {
    e.preventDefault()
    resizing = true
    document.addEventListener('mousemove', onResizeMove)
    document.addEventListener('mouseup', onResizeEnd)
  }

  function onResizeMove(e: MouseEvent) {
    if (!splitEl) return
    const rect = splitEl.getBoundingClientRect()
    splitPercent = clampSplit(((e.clientX - rect.left) / rect.width) * 100)
  }

  function onResizeEnd() {
    resizing = false
    localStorage.setItem(SPLIT_KEY, splitPercent.toFixed(1))
    document.removeEventListener('mousemove', onResizeMove)
    document.removeEventListener('mouseup', onResizeEnd)
  }

  function onResizeKey(e: KeyboardEvent) {
    if (e.key !== 'ArrowLeft' && e.key !== 'ArrowRight') return
    e.preventDefault()
    splitPercent = clampSplit(splitPercent + (e.key === 'ArrowLeft' ? -2 : 2))
    localStorage.setItem(SPLIT_KEY, splitPercent.toFixed(1))
  }

  onDestroy(() => {
    document.removeEventListener('mousemove', onResizeMove)
    document.removeEventListener('mouseup', onResizeEnd)
  })
</script>

{#if !dashboard}
  <div class="flex h-full flex-col items-center justify-center gap-1">
    <p class="text-[13px] text-fg-2">This dashboard is not available.</p>
    <p class="text-xs text-fg-3">It may still be loading, or it was deleted.</p>
  </div>
{:else}
  <div class="flex h-full flex-col">
    <div class="flex min-h-10 shrink-0 flex-wrap items-center gap-2 border-b border-edge-subtle px-3 py-1.5">
      <div class="min-w-0 flex-1">
        {#if isEditing && canEdit}
          <label class="sr-only" for="{uid}-name">Dashboard name</label>
          <Input
            id="{uid}-name"
            size="sm"
            class="max-w-xs font-medium"
            value={dashboard.name}
            oninput={(e) => rename(e.currentTarget.value)}
          />
        {:else}
          <p class="truncate text-[13px] font-medium text-fg">{parsed.title ?? dashboard.name}</p>
        {/if}
      </div>

      {#if lastRefreshedAt !== null && hasQueries}
        <span class="text-xs text-fg-3" title={new Date(lastRefreshedAt).toLocaleString()}>
          {hidden && intervalSeconds > 0 ? 'Paused · ' : ''}Updated {formatRelativeTime(lastRefreshedAt, Math.max(now, lastRefreshedAt))}
        </span>
      {/if}

      <div class="flex items-center gap-1" title="Auto-refresh (paused while this tab is hidden)">
        <Timer size={13} class="text-fg-3" />
        <label class="sr-only" for="{uid}-interval">Auto-refresh interval</label>
        <Select
          id="{uid}-interval"
          size="sm"
          class="w-36"
          value={String(selectedInterval)}
          options={intervalOptions}
          onchange={handleIntervalChange}
        />
      </div>

      <Button size="sm" variant="outline" onclick={refreshAll} disabled={!hasQueries} loading={refreshing}>
        {#if !refreshing}<RefreshCw size={13} />{/if}
        Refresh all
      </Button>

      <Button size="sm" variant="outline" onclick={() => (shareOpen = true)}>
        <Share2 size={13} />
        Share
      </Button>

      {#if !canEdit}
        <!-- Read-only is a workflow signal, not a lock: the document lives in
             this browser. Offer the honest path to editing, an owned copy. -->
        <Button size="sm" variant="outline" onclick={saveEditableCopy}>
          <Copy size={13} />
          Save editable copy
        </Button>
      {:else}
        <Button
          size="sm"
          variant={isEditing ? 'primary' : 'outline'}
          onclick={() => duckActions().setDashboardEditing(!isEditing)}
        >
          {#if isEditing}<Eye size={13} />{:else}<Pencil size={13} />{/if}
          {isEditing ? 'Done' : 'Edit'}
        </Button>
      {/if}
    </div>

    <div class="min-h-0 flex-1">
      {#if isEditing && canEdit}
        <div bind:this={splitEl} class="flex h-full min-w-0">
          <div class="min-w-0" style="width: {splitPercent}%">
            <DashboardSourceEditor
              value={source}
              onchange={handleSourceChange}
              {collabExtensions}
              ariaLabel="Source of {dashboard.name}"
            />
          </div>

          <!-- svelte-ignore a11y_no_noninteractive_tabindex -->
          <!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
          <div
            class="group/split flex w-1 shrink-0 cursor-col-resize items-center justify-center transition-colors hover:bg-active focus-visible:bg-active focus-visible:outline-none {resizing ? 'bg-accent/60' : 'bg-edge-subtle'}"
            role="separator"
            aria-orientation="vertical"
            aria-label="Resize source and preview"
            aria-valuemin={MIN_SPLIT}
            aria-valuemax={MAX_SPLIT}
            aria-valuenow={Math.round(splitPercent)}
            tabindex="0"
            onmousedown={onResizeStart}
            ondblclick={() => (splitPercent = 50)}
            onkeydown={onResizeKey}
          >
            <div class="h-8 w-0.5 rounded-full transition-colors {resizing ? 'bg-accent' : 'bg-edge-strong group-hover/split:bg-accent/60'}"></div>
          </div>

          <div class="min-w-0 flex-1 overflow-auto">
            <MarkdownDashboard blocks={parsed.blocks} {results} {inputs} {inputValues} />
          </div>
        </div>
      {:else}
        <div class="h-full overflow-auto">
          <MarkdownDashboard blocks={parsed.blocks} {results} {inputs} {inputValues} />
        </div>
      {/if}
    </div>
  </div>

  <ShareDashboardDialog
    open={shareOpen}
    onclose={() => (shareOpen = false)}
    {dashboard}
    onsharelive={onsharelive
      ? () => {
          shareOpen = false
          onsharelive()
        }
      : undefined}
  />

  {#if resizing}
    <div class="fixed inset-0 z-50 cursor-col-resize"></div>
  {/if}
{/if}

// src/components/dashboard/DashboardTab.tsx
import { useCallback, useEffect, useMemo, useRef, useState, useSyncExternalStore } from "react";
import { useDuckStore } from "@/store";
import { datasetsFor, getDashboardInputs, getDashboardRunner } from "@/store/slices/dashboardSlice";
import { datasetCacheKey } from "@/services/dashboard/queryRunner";
import { parseDashboardSource } from "@/services/dashboard/markdown";
import type { DatasetResult } from "@/services/dashboard/queryRunner";
import type { InputValue } from "@/services/dashboard/inputs";
import {
  decideRefresh,
  formatRefreshInterval,
  formatRelativeTime,
  latestFetchedAt,
  parseRefreshParam,
  REFRESH_INTERVAL_OPTIONS,
} from "@/services/dashboard/refresh";
import { enableDashboardCompletions } from "./dashboardCompletions";
import {
  createCellEditor,
  useMonacoConfig,
  type EditorInstance,
} from "@/components/editor/monacoConfig";
import { useTheme } from "@/components/theme/theme-provider";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ResizableHandle, ResizablePanel, ResizablePanelGroup } from "@/components/ui/resizable";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Copy, Eye, Loader2, Pencil, RefreshCw, Share2, Timer } from "lucide-react";
import ShareDashboardDialog from "./ShareDashboardDialog";
import ShareLiveDialog from "@/components/collaboration/ShareLiveDialog";
import MarkdownDashboard from "./MarkdownDashboard";
import { getCollaboration } from "@/store/slices/sessionSlice";
import {
  bindCollaborativeEditor,
  type CollaborativeBinding,
} from "@/components/editor/collaborativeBinding";
import type * as Y from "yjs";

interface DashboardTabProps {
  tabId: string;
}

/** Shared empty snapshots — a fresh Map per read would loop the subscription. */
const EMPTY_RESULTS: ReadonlyMap<string, DatasetResult> = new Map();
const EMPTY_INPUTS: ReadonlyMap<string, InputValue> = new Map();

const subscribeVisibility = (onChange: () => void) => {
  document.addEventListener("visibilitychange", onChange);
  return () => document.removeEventListener("visibilitychange", onChange);
};
const isDocumentHidden = () => document.visibilityState === "hidden";

/**
 * A dashboard document, as a workspace tab.
 *
 * View renders the document like a report. Edit is a split pane: markdown
 * source on the left, the live document on the right, re-rendered as you type.
 * The source is what persists and what a live session shares — the document IS
 * the dashboard.
 */
export default function DashboardTab({ tabId }: DashboardTabProps) {
  const tabs = useDuckStore((s) => s.tabs);
  const dashboards = useDuckStore((s) => s.dashboards);
  const isEditing = useDuckStore((s) => s.isDashboardEditing);
  const setEditing = useDuckStore((s) => s.setDashboardEditing);
  const updateDashboard = useDuckStore((s) => s.updateDashboard);
  const runDashboard = useDuckStore((s) => s.runDashboard);
  const duplicateDashboard = useDuckStore((s) => s.duplicateDashboard);
  const openDashboardTab = useDuckStore((s) => s.openDashboardTab);
  const engineReady = useDuckStore((s) => s.isInitialized);
  const sessionStatus = useDuckStore((s) => s.session.status);

  const tab = tabs.find((entry) => entry.id === tabId);
  const dashboardId = typeof tab?.content === "string" ? tab.content : "";
  const dashboard = dashboards.find((entry) => entry.id === dashboardId);

  const [refreshing, setRefreshing] = useState(false);
  const [shareOpen, setShareOpen] = useState(false);
  const [liveOpen, setLiveOpen] = useState(false);
  // The draft leads while typing; the store catches up on a debounce. Null
  // means "no local edits pending" and the stored source is authoritative.
  const [draft, setDraft] = useState<string | null>(null);
  const source = draft ?? dashboard?.source ?? "";

  const parsed = useMemo(() => parseDashboardSource(source), [source]);

  // Results come from the runner, not the store — a refresh must not push
  // every batch through a Zustand subscription.
  const subscribe = useCallback(
    (onChange: () => void) =>
      dashboardId ? getDashboardRunner(dashboardId).onChange(onChange) : () => {},
    [dashboardId]
  );
  const getSnapshot = useCallback(
    () => (dashboardId ? getDashboardRunner(dashboardId).snapshot() : EMPTY_RESULTS),
    [dashboardId]
  );
  const results = useSyncExternalStore(subscribe, getSnapshot, getSnapshot);

  // Input values, same pattern: view state living beside the runner.
  const subscribeInputs = useCallback(
    (onChange: () => void) =>
      dashboardId ? getDashboardInputs(dashboardId).subscribe(onChange) : () => {},
    [dashboardId]
  );
  const getInputsSnapshot = useCallback(
    () => (dashboardId ? getDashboardInputs(dashboardId).snapshot() : EMPTY_INPUTS),
    [dashboardId]
  );
  const inputValues = useSyncExternalStore(subscribeInputs, getInputsSnapshot, getInputsSnapshot);

  // Debounced persistence of edits.
  const saveTimer = useRef<ReturnType<typeof setTimeout>>(undefined);
  const handleSourceChange = useCallback(
    (value: string) => {
      setDraft(value);
      clearTimeout(saveTimer.current);
      saveTimer.current = setTimeout(() => {
        const current = useDuckStore.getState().dashboards.find((d) => d.id === dashboardId);
        if (current) void updateDashboard({ ...current, source: value });
      }, 600);
    },
    [dashboardId, updateDashboard]
  );
  useEffect(() => () => clearTimeout(saveTimer.current), []);

  // Run whatever the document declares, whenever the set of queries changes.
  // Keyed on name+sql: editing a query re-runs it, editing prose does not.
  // `engineReady` is a dependency for the reload path: a restored dashboard
  // tab renders BEFORE the WASM engine finishes booting, so the first run
  // fails with "connection not available" — and without re-running when the
  // engine arrives, it would stay failed forever.
  const querySignature = parsed.queries.map((query) => `${query.name}:${query.sql}`).join(" ");
  const lastRunKeys = useRef(new Map<string, string>());
  useEffect(() => {
    if (!engineReady || !dashboardId || !dashboard || parsed.queries.length === 0) return;
    const runner = getDashboardRunner(dashboardId);
    // Only datasets whose FINAL SQL changed re-run. Turning a date picker must
    // re-run the queries that reference it and leave the rest untouched.
    for (const dataset of datasetsFor({ ...dashboard, source }, inputValues)) {
      const key = datasetCacheKey(dataset);
      if (lastRunKeys.current.get(dataset.id) === key) continue;
      lastRunKeys.current.set(dataset.id, key);
      void runner.run(dataset);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [dashboardId, querySignature, engineReady, inputValues]);

  // ── Auto-refresh ──────────────────────────────────────────────────────
  // `?refresh=<seconds>` on the page URL is a kiosk override: it applies to
  // every dashboard opened in this page load and is never persisted. Picking
  // an interval in the toolbar drops the override and saves the choice.
  const [urlRefresh, setUrlRefresh] = useState(() =>
    typeof window === "undefined" ? null : parseRefreshParam(window.location.search)
  );
  const intervalSeconds =
    parsed.queries.length === 0 || !engineReady
      ? 0
      : (urlRefresh ?? dashboard?.refreshIntervalSeconds ?? 0);
  const hidden = useSyncExternalStore(subscribeVisibility, isDocumentHidden, () => false);
  const anyLoading = useMemo(
    () => [...results.values()].some((result) => result.status === "loading"),
    [results]
  );
  const inFlight = refreshing || anyLoading;
  // Completed-refresh time, including ones where every query failed (those
  // carry no fetchedAt, but still count as "we tried" for scheduling).
  const [lastAttemptAt, setLastAttemptAt] = useState<number | null>(null);
  const lastFetchedAt = useMemo(() => latestFetchedAt(results.values()), [results]);
  const lastRefreshedAt =
    lastAttemptAt === null
      ? lastFetchedAt
      : lastFetchedAt === null
        ? lastAttemptAt
        : Math.max(lastAttemptAt, lastFetchedAt);

  const refreshAll = useCallback(async () => {
    if (!dashboardId) return;
    setRefreshing(true);
    try {
      await runDashboard(dashboardId, true);
    } finally {
      setRefreshing(false);
      setLastAttemptAt(Date.now());
    }
  }, [dashboardId, runDashboard]);

  // One timer at a time, re-armed whenever any input to the decision changes.
  // `wake` bumps when a wait elapses so the decision is re-evaluated.
  const [wake, setWake] = useState(0);
  useEffect(() => {
    const decision = decideRefresh({
      intervalSeconds,
      // Enabling the interval before anything has loaded anchors on "now".
      lastRefreshedAt,
      now: Date.now(),
      hidden,
      inFlight,
    });
    if (decision.action === "idle") return;
    const timer = setTimeout(
      () => {
        if (decision.action === "refresh") void refreshAll();
        else setWake((count) => count + 1);
      },
      decision.action === "refresh" ? 0 : decision.delayMs
    );
    return () => clearTimeout(timer);
  }, [intervalSeconds, lastRefreshedAt, hidden, inFlight, refreshAll, wake]);

  // Anchor the first scheduled run when the interval turns on with nothing
  // loaded yet, so it fires one interval later rather than never.
  useEffect(() => {
    if (intervalSeconds <= 0 || lastRefreshedAt !== null) return;
    const timer = setTimeout(() => setLastAttemptAt(Date.now()), 0);
    return () => clearTimeout(timer);
  }, [intervalSeconds, lastRefreshedAt]);

  // Keeps the "updated … ago" label moving without re-rendering per second.
  const [now, setNow] = useState(() => Date.now());
  useEffect(() => {
    if (lastRefreshedAt === null) return;
    const update = () => setNow(Date.now());
    const timer = setInterval(update, 15_000);
    const initial = setTimeout(update, 0);
    return () => {
      clearInterval(timer);
      clearTimeout(initial);
    };
  }, [lastRefreshedAt]);

  if (!dashboard) {
    return (
      <div className="flex h-full flex-col items-center justify-center gap-1">
        <p className="text-sm text-muted-foreground">This dashboard is not available.</p>
        <p className="text-xs text-muted-foreground">It may still be loading, or it was deleted.</p>
      </div>
    );
  }

  const handleIntervalChange = (value: string) => {
    setUrlRefresh(null);
    const seconds = Number(value);
    void updateDashboard({
      ...dashboard,
      refreshIntervalSeconds: seconds > 0 ? seconds : undefined,
    });
  };
  const selectedInterval = urlRefresh ?? dashboard.refreshIntervalSeconds ?? 0;
  const intervalOptions = REFRESH_INTERVAL_OPTIONS.some(
    (option) => option.seconds === selectedInterval
  )
    ? REFRESH_INTERVAL_OPTIONS
    : [...REFRESH_INTERVAL_OPTIONS, { seconds: selectedInterval, label: "" }];

  return (
    <div className="flex h-full flex-col">
      <div className="flex flex-wrap items-center gap-2 border-b px-4 py-2">
        <div className="min-w-0 flex-1">
          {isEditing ? (
            <Input
              value={dashboard.name}
              onChange={(event) => updateDashboard({ ...dashboard, name: event.target.value })}
              className="h-7 max-w-xs text-sm font-medium"
              aria-label="Dashboard name"
            />
          ) : (
            <p className="truncate text-sm font-medium">{parsed.title ?? dashboard.name}</p>
          )}
        </div>

        {lastRefreshedAt !== null && parsed.queries.length > 0 && (
          <span
            className="text-xs text-muted-foreground"
            title={new Date(lastRefreshedAt).toLocaleString()}
          >
            {hidden && intervalSeconds > 0 ? "Paused · " : ""}
            Updated {formatRelativeTime(lastRefreshedAt, Math.max(now, lastRefreshedAt))}
          </span>
        )}

        <Select value={String(selectedInterval)} onValueChange={handleIntervalChange}>
          <SelectTrigger
            className="h-7 w-auto gap-1.5 px-2 text-xs"
            aria-label="Auto-refresh interval"
            title="Auto-refresh (paused while this tab is hidden)"
          >
            <Timer className="h-3.5 w-3.5" />
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            {intervalOptions.map((option) => (
              <SelectItem key={option.seconds} value={String(option.seconds)} className="text-xs">
                {option.seconds === 0
                  ? "Auto-refresh off"
                  : `Every ${formatRefreshInterval(option.seconds)}`}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>

        <Button
          size="sm"
          variant="outline"
          onClick={() => void refreshAll()}
          disabled={refreshing || parsed.queries.length === 0}
          className="h-7 gap-1.5 text-xs"
        >
          {refreshing ? (
            <Loader2 className="h-3.5 w-3.5 animate-spin" />
          ) : (
            <RefreshCw className="h-3.5 w-3.5" />
          )}
          Refresh all
        </Button>

        <Button
          size="sm"
          variant="outline"
          onClick={() => setShareOpen(true)}
          className="h-7 gap-1.5 text-xs"
        >
          <Share2 className="h-3.5 w-3.5" />
          Share
        </Button>

        {dashboard.role === "viewer" ? (
          // Read-only is a workflow signal, not a lock — the document lives in
          // this browser. Offer the honest path to editing: an owned copy.
          <Button
            size="sm"
            variant="outline"
            className="h-7 gap-1.5 text-xs"
            onClick={async () => {
              const copy = await duplicateDashboard(dashboard.id);
              if (copy) openDashboardTab(copy.id, copy.name);
            }}
          >
            <Copy className="h-3.5 w-3.5" />
            Save editable copy
          </Button>
        ) : (
          <Button
            size="sm"
            variant={isEditing ? "default" : "outline"}
            onClick={() => setEditing(!isEditing)}
            className="h-7 gap-1.5 text-xs"
          >
            {isEditing ? <Eye className="h-3.5 w-3.5" /> : <Pencil className="h-3.5 w-3.5" />}
            {isEditing ? "Done" : "Edit"}
          </Button>
        )}
      </div>

      <ShareDashboardDialog
        open={shareOpen}
        onOpenChange={setShareOpen}
        dashboard={dashboard}
        onShareLive={() => {
          setShareOpen(false);
          setLiveOpen(true);
        }}
      />
      <ShareLiveDialog open={liveOpen} onOpenChange={setLiveOpen} />

      <div className="min-h-0 flex-1">
        {isEditing && dashboard.role !== "viewer" ? (
          <ResizablePanelGroup direction="horizontal">
            <ResizablePanel defaultSize={50} minSize={25}>
              <SourceEditor
                tabId={tabId}
                initial={source}
                onChange={handleSourceChange}
                collabText={
                  sessionStatus === "connected"
                    ? (() => {
                        const collaboration = getCollaboration();
                        if (!collaboration) return null;
                        // Register on first edit in a session, so a dashboard
                        // opened mid-session becomes co-editable too.
                        collaboration.document.ensureDashboard(
                          dashboard.id,
                          dashboard.name,
                          source
                        );
                        return collaboration.document.dashboardText(dashboard.id);
                      })()
                    : null
                }
              />
            </ResizablePanel>
            <ResizableHandle withHandle />
            <ResizablePanel defaultSize={50} minSize={25}>
              <div className="h-full overflow-auto border-l">
                <MarkdownDashboard
                  blocks={parsed.blocks}
                  results={results}
                  inputs={dashboardId ? getDashboardInputs(dashboardId) : undefined}
                  inputValues={inputValues}
                />
              </div>
            </ResizablePanel>
          </ResizablePanelGroup>
        ) : (
          <div className="h-full overflow-auto">
            <MarkdownDashboard
              blocks={parsed.blocks}
              results={results}
              inputs={dashboardId ? getDashboardInputs(dashboardId) : undefined}
              inputValues={inputValues}
            />
          </div>
        )}
      </div>
    </div>
  );
}

/**
 * Monaco, in markdown mode.
 *
 * Uncontrolled on purpose: the editor owns the text while it is open, and
 * pushing debounced store updates back in as `setValue` would fight the caret
 * (the same rule the SQL editor learned the hard way).
 */
function SourceEditor({
  tabId,
  initial,
  onChange,
  collabText,
}: {
  tabId: string;
  initial: string;
  onChange: (value: string) => void;
  /** Shared Y.Text when a live session is running; edits then merge. */
  collabText?: Y.Text | null;
}) {
  const containerRef = useRef<HTMLDivElement>(null);
  const instanceRef = useRef<EditorInstance | null>(null);
  const { theme } = useTheme();
  const sqlConfig = useMonacoConfig(theme);
  const config = useMemo(
    // quickSuggestions ON: the whole point of the authoring experience is
    // that components, props, query names and input variables offer
    // themselves as you type (Ctrl+Space works everywhere regardless).
    // The full object, not `true`: markdown tokenizes component tags as
    // string-ish content, and boolean `true` leaves strings/comments off —
    // which silently kills suggestions exactly where this dialect needs them.
    () => ({
      ...sqlConfig,
      language: "markdown",
      quickSuggestions: { other: true, comments: true, strings: true },
    }),
    [sqlConfig]
  );

  const initialRef = useRef(initial);
  const onChangeRef = useRef(onChange);
  // Assigned in an effect, not during render — the lint rule is right that a
  // render-time ref write can tear under concurrent rendering.
  useEffect(() => {
    onChangeRef.current = onChange;
  }, [onChange]);

  useEffect(() => {
    if (!containerRef.current) return;
    instanceRef.current = createCellEditor(
      containerRef.current,
      config,
      initialRef.current,
      async () => {},
      (value) => onChangeRef.current(value)
    );

    // In a live session the source merges character-by-character through the
    // same binding the SQL editor uses. Store persistence still flows through
    // onChange, because remote edits arrive as model changes too.
    let binding: CollaborativeBinding | null = null;
    const editor = instanceRef.current.editor;
    const model = editor.getModel();
    // Dashboard-specific autocomplete: component tags, props, query names,
    // ${inputs.…} variables. Enrolled per model so notebook markdown and any
    // other markdown surface stay plain.
    const disableCompletions = model ? enableDashboardCompletions(model) : null;
    if (collabText && model) {
      const presence = getCollaboration()?.presence;
      binding = bindCollaborativeEditor({
        text: collabText,
        model,
        editor,
        presence: presence ?? undefined,
        tabId: `dashboard:${tabId}`,
      });
    }

    return () => {
      disableCompletions?.();
      binding?.destroy();
      // Flush before dispose: the cell editor debounces content changes, and
      // unmounting inside that window (typing, then immediately clicking
      // Done) would silently drop the last ~300ms of edits.
      const editor = instanceRef.current?.editor;
      if (editor) onChangeRef.current(editor.getValue());
      instanceRef.current?.dispose();
      instanceRef.current = null;
    };
  }, [tabId, config, collabText]);

  return <div ref={containerRef} className="h-full w-full" />;
}
