// src/lib/components/importer/CsvOptionsPanel.svelte
<script lang="ts">
  import Button from '../common/Button.svelte'
  import Input from '../common/Input.svelte'
  import FormField from '../common/FormField.svelte'
  import type { CsvImportOptions } from '@/lib/fileImporter/types'

  type OptionValue = string | boolean | number | undefined

  interface Props {
    /** Unique suffix for the field ids of this file. */
    idSuffix: string
    disabled: boolean
    csvOptions: CsvImportOptions
    onchange: (key: keyof CsvImportOptions, value: OptionValue) => void
  }

  let { idSuffix, disabled, csvOptions, onchange }: Props = $props()

  let showOptions = $state(false)

  const toggles: { key: 'header' | 'autoDetect' | 'ignoreErrors' | 'nullPadding'; label: string }[] = [
    { key: 'header', label: 'Has header row' },
    { key: 'autoDetect', label: 'Auto-detect types' },
    { key: 'ignoreErrors', label: 'Ignore errors' },
    { key: 'nullPadding', label: 'Pad missing columns' },
  ]

  const toCount = (raw: string): number | undefined => parseInt(raw, 10) || undefined
</script>

<div class="mt-3">
  <div class="flex items-center justify-between">
    <h4 class="text-xs font-medium text-fg-2">CSV import options</h4>
    <Button variant="ghost" size="xs" aria-expanded={showOptions} onclick={() => (showOptions = !showOptions)}>
      {showOptions ? 'Hide options' : 'Show options'}
    </Button>
  </div>

  {#if showOptions}
    <div class="mt-2 flex flex-col gap-3">
      <div class="grid grid-cols-2 gap-2">
        {#each toggles as toggle (toggle.key)}
          <label class="ds-checkbox-label text-xs">
            <input
              type="checkbox"
              class="ds-checkbox ds-checkbox-sm"
              checked={csvOptions[toggle.key]}
              {disabled}
              onchange={(e) => onchange(toggle.key, e.currentTarget.checked)}
            />
            {toggle.label}
          </label>
        {/each}
      </div>

      <FormField label="Delimiter" for="delimiter-{idSuffix}" hint="Common values: , (comma), ; (semicolon), tab, pipe (|)">
        <Input
          id="delimiter-{idSuffix}"
          size="sm"
          value={csvOptions.delimiter}
          placeholder="Delimiter character"
          {disabled}
          oninput={(e) => onchange('delimiter', e.currentTarget.value)}
        />
      </FormField>

      <div class="flex flex-col gap-3 border-t border-edge-subtle pt-3">
        <h5 class="text-xs font-medium text-fg-3">Advanced options</h5>

        <div class="grid grid-cols-2 gap-3">
          <FormField controlWidth="full" label="Quote character" for="quote-{idSuffix}">
            <Input
              id="quote-{idSuffix}"
              size="sm"
              value={csvOptions.quote ?? ''}
              placeholder={'" (default)'}
              {disabled}
              oninput={(e) => onchange('quote', e.currentTarget.value)}
            />
          </FormField>

          <FormField controlWidth="full" label="Escape character" for="escape-{idSuffix}">
            <Input
              id="escape-{idSuffix}"
              size="sm"
              value={csvOptions.escape ?? ''}
              placeholder={'" (default)'}
              {disabled}
              oninput={(e) => onchange('escape', e.currentTarget.value)}
            />
          </FormField>

          <FormField controlWidth="full" label="Skip rows" for="skip-{idSuffix}">
            <Input
              id="skip-{idSuffix}"
              size="sm"
              type="number"
              min={0}
              value={csvOptions.skip ?? ''}
              placeholder="0"
              {disabled}
              oninput={(e) => onchange('skip', toCount(e.currentTarget.value))}
            />
          </FormField>

          <FormField controlWidth="full" label="Sample size" for="sample-size-{idSuffix}">
            <Input
              id="sample-size-{idSuffix}"
              size="sm"
              type="number"
              min={1}
              value={csvOptions.sampleSize ?? ''}
              placeholder="Auto"
              {disabled}
              oninput={(e) => onchange('sampleSize', toCount(e.currentTarget.value))}
            />
          </FormField>
        </div>

        <FormField
          controlWidth="full"
          label="NULL string"
          for="null-str-{idSuffix}"
          hint="Values matching this string will be treated as NULL"
        >
          <Input
            id="null-str-{idSuffix}"
            size="sm"
            value={csvOptions.nullStr ?? ''}
            placeholder="Empty values treated as NULL"
            {disabled}
            oninput={(e) => onchange('nullStr', e.currentTarget.value)}
          />
        </FormField>

        <div class="grid grid-cols-2 gap-3">
          <FormField controlWidth="full" label="Date format" for="date-format-{idSuffix}">
            <Input
              id="date-format-{idSuffix}"
              size="sm"
              value={csvOptions.dateFormat ?? ''}
              placeholder="ISO 8601"
              {disabled}
              oninput={(e) => onchange('dateFormat', e.currentTarget.value)}
            />
          </FormField>

          <FormField controlWidth="full" label="Timestamp format" for="timestamp-format-{idSuffix}">
            <Input
              id="timestamp-format-{idSuffix}"
              size="sm"
              value={csvOptions.timestampFormat ?? ''}
              placeholder="ISO 8601"
              {disabled}
              oninput={(e) => onchange('timestampFormat', e.currentTarget.value)}
            />
          </FormField>
        </div>
      </div>
    </div>
  {/if}
</div>

// src/components/explorer/file-importer/CsvOptionsPanel.tsx
import React from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import type { CsvImportOptions, FileImportState, FileWithPreview } from "./types";

interface CsvOptionsPanelProps {
  file: FileWithPreview;
  status: FileImportState;
  csvOptions: CsvImportOptions;
  showAdvancedOptions: boolean;
  setShowAdvancedOptions: (show: boolean) => void;
  handleCsvOptionChange: (
    key: keyof CsvImportOptions,
    value: string | boolean | number | undefined
  ) => void;
}

const CsvOptionsPanel: React.FC<CsvOptionsPanelProps> = ({
  file,
  status,
  csvOptions,
  showAdvancedOptions,
  setShowAdvancedOptions,
  handleCsvOptionChange,
}) => {
  return (
    <div className="mt-4 space-y-3">
      <div className="flex justify-between items-center">
        <h4 className="font-medium text-sm">CSV Import Options</h4>
        <Button
          variant="ghost"
          size="sm"
          onClick={() => setShowAdvancedOptions(!showAdvancedOptions)}
        >
          {showAdvancedOptions ? "Hide Options" : "Show Options"}
        </Button>
      </div>

      {showAdvancedOptions && (
        <div className="p-3 rounded-md space-y-3">
          <div className="grid grid-cols-2 gap-2">
            <div className="flex items-center space-x-2">
              <input
                type="checkbox"
                id={`header-${file.name}`}
                checked={csvOptions.header}
                onChange={(e) => handleCsvOptionChange("header", e.target.checked)}
                disabled={status.status === "uploading" || status.status === "processing"}
                className="h-4 w-4 rounded border-gray-300 text-primary focus:ring-primary"
              />
              <Label htmlFor={`header-${file.name}`} className="text-sm">
                Has header row
              </Label>
            </div>

            <div className="flex items-center space-x-2">
              <input
                type="checkbox"
                id={`auto-detect-${file.name}`}
                checked={csvOptions.autoDetect}
                onChange={(e) => handleCsvOptionChange("autoDetect", e.target.checked)}
                disabled={status.status === "uploading" || status.status === "processing"}
                className="h-4 w-4 rounded border-gray-300 text-primary focus:ring-primary"
              />
              <Label htmlFor={`auto-detect-${file.name}`} className="text-sm">
                Auto-detect types
              </Label>
            </div>

            <div className="flex items-center space-x-2">
              <input
                type="checkbox"
                id={`ignore-errors-${file.name}`}
                checked={csvOptions.ignoreErrors}
                onChange={(e) => handleCsvOptionChange("ignoreErrors", e.target.checked)}
                disabled={status.status === "uploading" || status.status === "processing"}
                className="h-4 w-4 rounded border-gray-300 text-primary focus:ring-primary"
              />
              <Label htmlFor={`ignore-errors-${file.name}`} className="text-sm">
                Ignore errors
              </Label>
            </div>

            <div className="flex items-center space-x-2">
              <input
                type="checkbox"
                id={`null-padding-${file.name}`}
                checked={csvOptions.nullPadding}
                onChange={(e) => handleCsvOptionChange("nullPadding", e.target.checked)}
                disabled={status.status === "uploading" || status.status === "processing"}
                className="h-4 w-4 rounded border-gray-300 text-primary focus:ring-primary"
              />
              <Label htmlFor={`null-padding-${file.name}`} className="text-sm">
                Pad missing columns
              </Label>
            </div>
          </div>

          <div className="space-y-1">
            <Label htmlFor={`delimiter-${file.name}`} className="text-sm">
              Delimiter
            </Label>
            <div className="max-w-xs">
              <Input
                id={`delimiter-${file.name}`}
                value={csvOptions.delimiter}
                onChange={(e) => handleCsvOptionChange("delimiter", e.target.value)}
                placeholder="Delimiter character"
                className="h-8"
                disabled={status.status === "uploading" || status.status === "processing"}
              />
            </div>
            <p className="text-xs text-gray-500">
              Common values: , (comma), ; (semicolon), tab, pipe (|)
            </p>
          </div>

          {/* Advanced CSV Options */}
          <div className="space-y-3 pt-3 border-t">
            <h5 className="font-medium text-sm text-muted-foreground">Advanced Options</h5>

            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1">
                <Label htmlFor={`quote-${file.name}`} className="text-xs">
                  Quote Character
                </Label>
                <Input
                  id={`quote-${file.name}`}
                  value={csvOptions.quote || ""}
                  onChange={(e) => handleCsvOptionChange("quote", e.target.value)}
                  placeholder={`" (default)`}
                  className="h-8 text-xs"
                  disabled={status.status === "uploading" || status.status === "processing"}
                />
              </div>

              <div className="space-y-1">
                <Label htmlFor={`escape-${file.name}`} className="text-xs">
                  Escape Character
                </Label>
                <Input
                  id={`escape-${file.name}`}
                  value={csvOptions.escape || ""}
                  onChange={(e) => handleCsvOptionChange("escape", e.target.value)}
                  placeholder={`" (default)`}
                  className="h-8 text-xs"
                  disabled={status.status === "uploading" || status.status === "processing"}
                />
              </div>

              <div className="space-y-1">
                <Label htmlFor={`skip-${file.name}`} className="text-xs">
                  Skip Rows
                </Label>
                <Input
                  id={`skip-${file.name}`}
                  type="number"
                  min="0"
                  value={csvOptions.skip || ""}
                  onChange={(e) =>
                    handleCsvOptionChange("skip", parseInt(e.target.value, 10) || undefined)
                  }
                  placeholder="0"
                  className="h-8 text-xs"
                  disabled={status.status === "uploading" || status.status === "processing"}
                />
              </div>

              <div className="space-y-1">
                <Label htmlFor={`sample-size-${file.name}`} className="text-xs">
                  Sample Size
                </Label>
                <Input
                  id={`sample-size-${file.name}`}
                  type="number"
                  min="1"
                  value={csvOptions.sampleSize || ""}
                  onChange={(e) =>
                    handleCsvOptionChange("sampleSize", parseInt(e.target.value, 10) || undefined)
                  }
                  placeholder="Auto"
                  className="h-8 text-xs"
                  disabled={status.status === "uploading" || status.status === "processing"}
                />
              </div>
            </div>

            <div className="space-y-1">
              <Label htmlFor={`null-str-${file.name}`} className="text-xs">
                NULL String
              </Label>
              <Input
                id={`null-str-${file.name}`}
                value={csvOptions.nullStr || ""}
                onChange={(e) => handleCsvOptionChange("nullStr", e.target.value)}
                placeholder="Empty values treated as NULL"
                className="h-8 text-xs"
                disabled={status.status === "uploading" || status.status === "processing"}
              />
              <p className="text-xs text-muted-foreground">
                Values matching this string will be treated as NULL
              </p>
            </div>

            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-1">
                <Label htmlFor={`date-format-${file.name}`} className="text-xs">
                  Date Format
                </Label>
                <Input
                  id={`date-format-${file.name}`}
                  value={csvOptions.dateFormat || ""}
                  onChange={(e) => handleCsvOptionChange("dateFormat", e.target.value)}
                  placeholder="ISO 8601"
                  className="h-8 text-xs"
                  disabled={status.status === "uploading" || status.status === "processing"}
                />
              </div>

              <div className="space-y-1">
                <Label htmlFor={`timestamp-format-${file.name}`} className="text-xs">
                  Timestamp Format
                </Label>
                <Input
                  id={`timestamp-format-${file.name}`}
                  value={csvOptions.timestampFormat || ""}
                  onChange={(e) => handleCsvOptionChange("timestampFormat", e.target.value)}
                  placeholder="ISO 8601"
                  className="h-8 text-xs"
                  disabled={status.status === "uploading" || status.status === "processing"}
                />
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default CsvOptionsPanel;
