// src/lib/components/importer/PreviewPanel.svelte
<script lang="ts">
  import { ArrowLeft, Check } from 'lucide-svelte'
  import type { QueryResult } from '@/store'
  import Button from '../common/Button.svelte'
  import VirtualTable from '../table/VirtualTable.svelte'
  import ErrorAlertList from './ErrorAlertList.svelte'
  import SchemaEditor from './SchemaEditor.svelte'
  import { PREVIEW_ROW_LIMIT } from '@/lib/fileImporter/constants'
  import type { UrlImport } from '@/lib/fileImporter/urlImport.svelte'
  import type { UploadError } from '@/lib/fileImporter/types'

  interface Props {
    url: UrlImport
    previewData: QueryResult
    errors: UploadError[]
  }

  let { url, previewData, errors }: Props = $props()

  const meta = $derived(
    previewData.columns.map((name, idx) => ({ name, type: previewData.columnTypes[idx] ?? '' }))
  )
  const rows = $derived(previewData.data.map((row) => previewData.columns.map((name) => row[name])))
  const shortName = $derived(
    url.previewFileName.length > 50 ? `...${url.previewFileName.slice(-47)}` : url.previewFileName
  )
</script>

<!-- Preview of a URL source before importing it, with optional schema edits. -->
<div class="flex flex-col gap-4">
  <div class="flex items-start justify-between gap-3 rounded-md border border-edge bg-surface p-3">
    <div class="min-w-0">
      <h3 class="truncate text-[13px] font-semibold text-fg" title={url.previewFileName}>Preview: {shortName}</h3>
      <p class="mt-0.5 text-xs text-fg-3">
        Table name: <span class="font-mono text-fg-2">{url.previewTableName}</span>
      </p>
      <p class="mt-0.5 text-xs text-fg-4">
        Showing first {PREVIEW_ROW_LIMIT} rows, {previewData.rowCount} loaded
      </p>
    </div>
    <Button variant="ghost" size="sm" onclick={url.handleBackFromPreview}>
      <ArrowLeft size={14} />
      Back
    </Button>
  </div>

  <div class="flex h-[400px] overflow-hidden rounded-md border border-edge">
    <VirtualTable {meta} data={rows} />
  </div>

  <SchemaEditor {url} />

  <div class="flex justify-end gap-2">
    <Button variant="outline" onclick={url.handleBackFromPreview}>Cancel</Button>
    <Button onclick={url.handleImportFromPreview} loading={url.isUrlImporting}>
      {#if url.isUrlImporting}
        Importing...
      {:else}
        <Check size={14} />
        Import table
      {/if}
    </Button>
  </div>

  {#if errors.length > 0}
    <ErrorAlertList {errors} />
  {/if}
</div>

// src/components/explorer/file-importer/PreviewPanel.tsx
import React from "react";
import { Loader2, ArrowLeft, Check } from "lucide-react";
import type { QueryResult } from "@/store";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import DuckUITable from "@/components/table/DuckUItable";
import { PREVIEW_ROW_LIMIT } from "./constants";
import { ErrorAlertList } from "./ErrorAlerts";
import SchemaEditor, { type SchemaEditorProps } from "./SchemaEditor";
import type { UploadError } from "./types";

interface PreviewPanelProps extends SchemaEditorProps {
  previewData: QueryResult;
  previewFileName: string;
  previewTableName: string;
  isUrlImporting: boolean;
  errors: UploadError[];
  handleBackFromPreview: () => void;
  handleImportFromPreview: () => void;
}

/** Preview of a URL source before importing it, with optional schema edits. */
const PreviewPanel: React.FC<PreviewPanelProps> = ({
  previewData,
  previewFileName,
  previewTableName,
  isUrlImporting,
  errors,
  handleBackFromPreview,
  handleImportFromPreview,
  schemaColumns,
  isSchemaCustomizing,
  setIsSchemaCustomizing,
  handleToggleColumn,
  handleRenameColumn,
  handleChangeColumnType,
}) => {
  return (
    <div className="space-y-4">
      {/* Header with file info and navigation */}
      <Card>
        <CardContent className="p-4">
          <div className="flex items-start justify-between mb-3">
            <div className="flex-1">
              <h3 className="font-semibold text-lg mb-1">
                Preview:{" "}
                {previewFileName.length > 50 ? `...${previewFileName.slice(-47)}` : previewFileName}
              </h3>
              <p className="text-sm text-muted-foreground">
                Table Name: <span className="font-mono">{previewTableName}</span>
              </p>
              <p className="text-xs text-muted-foreground mt-1">
                Showing first {PREVIEW_ROW_LIMIT} rows • {previewData.rowCount} total rows
              </p>
            </div>
            <Button variant="ghost" size="sm" onClick={handleBackFromPreview}>
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Preview Table */}
      <Card>
        <CardContent className="p-4">
          <DuckUITable data={previewData.data} initialPageSize={20} tableHeight="400px" />
        </CardContent>
      </Card>

      {/* Schema Customization */}
      <SchemaEditor
        schemaColumns={schemaColumns}
        isSchemaCustomizing={isSchemaCustomizing}
        setIsSchemaCustomizing={setIsSchemaCustomizing}
        handleToggleColumn={handleToggleColumn}
        handleRenameColumn={handleRenameColumn}
        handleChangeColumnType={handleChangeColumnType}
      />

      {/* Action Buttons */}
      <div className="flex gap-2 justify-end">
        <Button variant="outline" onClick={handleBackFromPreview}>
          Cancel
        </Button>
        <Button onClick={handleImportFromPreview} disabled={isUrlImporting}>
          {isUrlImporting ? (
            <>
              <Loader2 className="w-4 h-4 mr-2 animate-spin" />
              Importing...
            </>
          ) : (
            <>
              <Check className="w-4 h-4 mr-2" />
              Import Table
            </>
          )}
        </Button>
      </div>

      {/* Errors */}
      {errors.length > 0 && <ErrorAlertList errors={errors} />}
    </div>
  );
};

export default PreviewPanel;
