// src/lib/components/importer/UploadTab.svelte
<script lang="ts">
  import { Upload, X } from 'lucide-svelte'
  import Button from '../common/Button.svelte'
  import ErrorAlertList from './ErrorAlertList.svelte'
  import FileDetails from './FileDetails.svelte'
  import ImportModeSwitch from './ImportModeSwitch.svelte'
  import { ACCEPTED_FILE_TYPES, MAX_FILE_SIZE } from '@/lib/fileImporter/constants'
  import { formatFileSize } from '@/lib/fileImporter/helpers'
  import type { LocalFileImport } from '@/lib/fileImporter/localFileImport.svelte'
  import type { ImportMode, UploadError } from '@/lib/fileImporter/types'

  interface Props {
    local: LocalFileImport
    importMode: ImportMode
    onmodechange: (mode: ImportMode) => void
    errors: UploadError[]
  }

  let { local, importMode, onmodechange, errors }: Props = $props()

  let fileInput: HTMLInputElement | undefined = $state()

  const accept = Object.values(ACCEPTED_FILE_TYPES).flat().join(',')
</script>

<!-- "Upload Files" tab: drop zone, per-file settings and the import button.
     Drops are handled by the importer shell, so the whole sheet is a target. -->
<div class="flex flex-col gap-4">
  <div
    class="flex min-h-[180px] flex-col items-center justify-center rounded-lg border border-dashed p-6 text-center transition-colors {local.isDragActive ? 'border-accent bg-accent-soft' : 'border-edge-strong'}"
  >
    <input
      bind:this={fileInput}
      type="file"
      multiple
      hidden
      {accept}
      aria-label="Select files to import"
      onchange={local.handleFileInputChange}
    />
    <Upload size={28} strokeWidth={1.5} class="mb-3 {local.isDragActive ? 'text-accent' : 'text-fg-4'}" />
    {#if local.isDragActive}
      <p class="text-[13px] font-medium text-accent">Drop the files here ...</p>
    {:else}
      <p class="text-[13px] font-medium text-fg">Drag and drop files here, or</p>
      <Button class="mt-2" variant="outline" size="sm" onclick={() => fileInput?.click()}>Select files</Button>
      <p class="mt-3 text-xs text-fg-3">Supported formats: CSV, JSON, Parquet, Arrow and DuckDB</p>
      <p class="mt-0.5 text-xs text-fg-4">Maximum file size: {formatFileSize(MAX_FILE_SIZE)}</p>
    {/if}
  </div>

  {#if local.hasFilesToImport}
    <div class="flex flex-col gap-3">
      <div class="flex items-center justify-between gap-3">
        <h3 class="text-[13px] font-semibold text-fg">Files to import</h3>
        <div class="flex items-center gap-2">
          <span class="text-xs text-fg-3">Mode:</span>
          <ImportModeSwitch value={importMode} onchange={onmodechange} tableLabel="Import (Table)" viewLabel="Link (View)" />
        </div>
      </div>
      {#if importMode === 'view'}
        <p class="text-xs text-fg-3">
          Views reference the original file without copying data. Queries re-read the file each time, using less memory
          but may be slower.
        </p>
      {/if}
      {#each local.files as file (file.name)}
        <FileDetails
          {file}
          tableName={local.tableNames[file.name] ?? ''}
          ontablenamechange={(name) => local.setTableName(file.name, name)}
          status={local.importStates[file.name] ?? { fileName: file.name, status: 'pending' }}
          csvOptions={local.csvOptions[file.name]}
          oncsvoptionschange={(options) => local.setCsvOptions(file.name, options)}
          onremove={() => local.removeFile(file.name)}
          onretry={() => local.retryFileUpload(file.name)}
        />
      {/each}
    </div>
  {/if}

  {#if errors.length > 0}
    <ErrorAlertList {errors} detailed />
  {/if}

  {#if local.hasFilesToImport}
    <div class="flex gap-2">
      <Button class="flex-1" onclick={local.handleFileUpload} loading={local.isUploading}>
        {#if local.isUploading}
          Importing files...
        {:else}
          <Upload size={14} />
          Import {local.files.length} {local.files.length === 1 ? 'file' : 'files'}
        {/if}
      </Button>
      {#if local.isUploading}
        <Button variant="danger" onclick={local.handleCancelUpload}>
          <X size={14} />
          Cancel
        </Button>
      {/if}
    </div>
  {/if}
</div>

// src/components/explorer/file-importer/UploadTab.tsx
import React from "react";
import { Upload, Loader2, X } from "lucide-react";
import { CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { TabsContent } from "@/components/ui/tabs";
import { cn } from "@/lib/utils";
import { ACCEPTED_FILE_TYPES, MAX_FILE_SIZE } from "./constants";
import { UploadErrorAlertList } from "./ErrorAlerts";
import FileDetails from "./FileDetails";
import { formatFileSize } from "./helpers";
import type { ImportMode, UploadError } from "./types";
import type { LocalFileImport } from "./useLocalFileImport";

interface UploadTabProps extends LocalFileImport {
  importMode: ImportMode;
  setImportMode: (mode: ImportMode) => void;
  errors: UploadError[];
}

/** "Upload Files" tab: drop zone, per-file settings and the import button. */
const UploadTab: React.FC<UploadTabProps> = ({
  importMode,
  setImportMode,
  errors,
  files,
  tableNames,
  setTableNames,
  isUploading,
  importStates,
  csvOptions,
  setCsvOptions,
  isDragActive,
  fileInputRef,
  hasFilesToImport,
  handleDrop,
  handleDragOver,
  handleDragLeave,
  handleFileInputChange,
  handleFileUpload,
  handleCancelUpload,
  removeFile,
  retryFileUpload,
}) => {
  return (
    <TabsContent value="upload" className="space-y-4 mt-4">
      <CardContent className="space-y-4 p-0">
        <div
          onDrop={handleDrop}
          onDragOver={handleDragOver}
          onDragLeave={handleDragLeave}
          className={cn(
            "border-2 border-dashed rounded-lg p-8 text-center cursor-pointer",
            "transition-colors duration-200 min-h-[200px] flex flex-col items-center justify-center",
            isDragActive
              ? "border-primary bg-primary/10"
              : "border-gray-300 hover:border-primary hover:bg-primary/10"
          )}
        >
          <Input
            type="file"
            multiple
            hidden
            ref={fileInputRef}
            accept={Object.values(ACCEPTED_FILE_TYPES).flat().join(",")}
            onChange={handleFileInputChange}
          />
          <Upload
            className={cn(
              "w-12 h-12 mb-4 mt-4",
              isDragActive ? "text-accent" : "text-muted-foreground"
            )}
          />
          {isDragActive ? (
            <p className="text-blue-500 font-medium">Drop the files here ...</p>
          ) : (
            <>
              <div className="space-y-2">
                <p className="font-medium">Drag & drop files here, or</p>
                <Button variant="outline" onClick={() => fileInputRef.current?.click()}>
                  Select Files
                </Button>
                <p className="text-sm text-gray-500">
                  Supported formats: CSV, JSON, Parquet, Arrow and DuckDB
                </p>
                <p className="text-xs text-gray-400">
                  Maximum file size: {formatFileSize(MAX_FILE_SIZE)}
                </p>
              </div>
            </>
          )}
        </div>

        {hasFilesToImport && (
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <h3 className="font-medium text-lg">Files to Import</h3>
              <div className="flex items-center gap-2">
                <span className="text-sm text-muted-foreground">Mode:</span>
                <div className="flex rounded-md border">
                  <Button
                    variant={importMode === "table" ? "default" : "ghost"}
                    size="sm"
                    className="rounded-r-none h-7 text-xs"
                    onClick={() => setImportMode("table")}
                  >
                    Import (Table)
                  </Button>
                  <Button
                    variant={importMode === "view" ? "default" : "ghost"}
                    size="sm"
                    className="rounded-l-none h-7 text-xs"
                    onClick={() => setImportMode("view")}
                  >
                    Link (View)
                  </Button>
                </div>
              </div>
            </div>
            {importMode === "view" && (
              <p className="text-xs text-muted-foreground">
                Views reference the original file without copying data. Queries re-read the file
                each time, using less memory but may be slower.
              </p>
            )}
            <div className="space-y-3">
              {files.map((file) => {
                const fileType = file.name.split(".").pop()?.toLowerCase();
                const isCsvFile = fileType === "csv";

                return (
                  <FileDetails
                    key={file.name}
                    file={file}
                    tableName={tableNames[file.name] || ""}
                    onTableNameChange={(name) =>
                      setTableNames((prev) => ({
                        ...prev,
                        [file.name]: name,
                      }))
                    }
                    status={
                      importStates[file.name] || {
                        fileName: file.name,
                        status: "pending",
                      }
                    }
                    csvOptions={isCsvFile ? csvOptions[file.name] : undefined}
                    onCsvOptionsChange={
                      isCsvFile
                        ? (options) =>
                            setCsvOptions((prev) => ({
                              ...prev,
                              [file.name]: options,
                            }))
                        : undefined
                    }
                    onRemove={() => removeFile(file.name)}
                    onRetry={() => retryFileUpload(file.name)}
                  />
                );
              })}
            </div>
          </div>
        )}

        {errors.length > 0 && <UploadErrorAlertList errors={errors} />}

        {hasFilesToImport && (
          <div className="flex gap-2">
            <Button onClick={handleFileUpload} disabled={isUploading} className="flex-1">
              {isUploading ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Importing Files...
                </>
              ) : (
                <>
                  <Upload className="w-4 h-4 mr-2" />
                  Import {files.length} {files.length === 1 ? "File" : "Files"}
                </>
              )}
            </Button>

            {isUploading && (
              <Button
                variant="destructive"
                onClick={handleCancelUpload}
                className="whitespace-nowrap"
              >
                <X className="w-4 h-4 mr-2" />
                Cancel
              </Button>
            )}
          </div>
        )}
      </CardContent>
    </TabsContent>
  );
};

export default UploadTab;
